const arrYoutube = [


{ 	id: 'asmr', title: 'ASMR', 
	nav: [ 
		{ id: 'all' 	, title: 'Все' 		, },
		{ id: 'voice' 	, title: 'Голос' 	, },
		{ id: 'other' 	, title: 'Разное' 	, },
	],
	arr: [
		{ href: 'nka_upUVnu0', title: 'Alana - Relaxing Haircut' 									, cat: { voice: 1, } , },
		{ href: 'ARH4UfPdYqI', title: 'Alana - Mic Touching, Brushing, Fluffiness & Scratching' 	, cat: { voice: 1, } , },
		{ href: 'svJuAHw826E', title: 'Alana - Scissor and Tweezer' 								, cat: { voice: 1, } , },
		{ href: 'Bsh7OA8_M-E', title: 'Freds Voice - Bring Back The Tingles YOU Deserve' 			, cat: { voice: 1, } , },
		{ href: 'XgRnPbKA7ug', title: 'Freds Voice - Ultra Fast RAW Barbershop' 					, cat: { voice: 1, } , },
		{ href: '8hkGXGZZJpg', title: 'Darling - Doctor Roleplay' 									, cat: { voice: 1, } , },
		{ href: 'CbFtevW1WQs', title: 'Cosmic Tingles - Heart Doctor' 								, cat: { voice: 1, } , },
		{ href: '7MekvHvdufA', title: 'Lizi - Medical RP' 											, cat: { voice: 1, } , },
		{ href: 'rUoO4t6J2YU', title: 'Lizi - Most Relaxing Ear Cleaning' 							, cat: { voice: 1, } , },
		{ href: 'ZkQGMz8F6is', title: 'Lizi - Tingly Face Examination' 								, cat: { voice: 1, } , },
		{ href: 's-YbJPuegt8', title: 'MissCoookiez - Ethan Carter' 								, cat: { voice: 1, } , },
		{ href: 'Ac5qu4MySVg', title: 'MissCoookiez - Painting Space' 								, cat: { voice: 1, } , },
		{ href: 'dy2dweAjVA0', title: 'Mood - Невролог' 											, cat: { voice: 1, } , },
		{ href: 'gjs2nVppdHo', title: 'Slikhaar TV - Mens hair' 									, cat: { voice: 1, } , },
		{ href: 'R4y4pj-KosY', title: 'Soft - Cranial Nerve Exam' 									, cat: { voice: 1, } , },
		{ href: 'PkTRBG5ITJ0', title: 'Soft - Headache' 											, cat: { voice: 1, } , },
		{ href: '92XOI5nNgik', title: 'Soft - Eye Exam' 											, cat: { voice: 1, } , },
		{ href: 'Hq3ZbN7Al3o', title: 'Sova - Невролог' 											, cat: { voice: 1, } , },
		{ href: '8uT-vVdXvCg', title: 'Tari - Tаможенница' 											, cat: { voice: 1, } , },
		{ href: 'kRJkCUE5bKQ', title: 'Ирина - Дерматолог' 											, cat: { voice: 1, } , },
		{ href: 'yPHKr4nQdrM', title: 'Автомат Калашникова' 										, cat: { other: 1, } , },
		{ href: 'uwnSMM5vBqo', title: 'Смена караула США' 											, cat: { other: 1, } , },
		{ href: 'pYc1FhYQndg', title: 'Толщиномер ЛКП - Nissan Murano 3.5 2007' 					, cat: { other: 1, } , },
		{ href: 'nro1zWh-U_w', title: 'Толщиномер ЛКП - Renault Grand Scenic' 						, cat: { other: 1, } , },
		{ href: 'aJb8P4Ya9PM', title: 'Толщиномер ЛКП - Тойота Королла' 							, cat: { other: 1, } , },
		{ href: '9lnUq32hXeo', title: 'Толщиномер ЛКП - Форд Фокус 2' 								, cat: { other: 1, } , },

	], 
},
{ 	
	id: 'comedy', title: 'Comedy', 
	nav: [ 
		{ id: 'all' 	, title: 'Все' 		, },
	],
	arr: [
		{ href: 'Vqh2Tx9ae2A', title: 'Comedy - Два крыла' 				, },
		{ href: 'taavmUs3biY', title: 'Comedy - Валентина, выпьем' 		, },
		{ href: 'HJQZUHSv9-s', title: 'Comedy - Подкаблучники' 			, },
		{ href: 'Km5VEGShtNc', title: 'Марина Кравец - Мурка' 			, },

	], 
},
{ 
	id: 'programming', title: 'Programming', 
	nav: [ 
		{ id: 'all' 		, title: 'Все' 			, },
		{ id: 'angular' 	, title: 'Angular' 		, },
		{ id: 'mongodb' 	, title: 'MongoDB' 		, },
		{ id: 'seo' 		, title: 'SEO' 			, },
	],
	arr: [

		{ href: 'Gl4IT4JpP4o' , title: 'javascript.ru' 		, cat: { angular: 1 , } 	, },
		{ href: 'Pww35rSOD7E' , title: 'To Do' 				, cat: { angular: 1 , } 	, },
		{ href: 's9Ig44UBr38' , title: 'WDB' 				, cat: { angular: 1 , } 	, },
		{ href: 'u1VCxpvDgsk' , title: 'Гоша Дударь' 		, cat: { angular: 1 , } 	, },
		{ href: 'GzQ_g0PkaHk' , title: 'КСХП' 				, cat: { angular: 1 , } 	, },
		{ href: 'xwr3azx0Gf0' , title: 'Гоша Дударь' 		, cat: { mongodb: 1 , } 	, list: 'PL0lO_mIqDDFXcxN3fRjc-EOWZLqW8dLVV', },
		{ href: 'dMWWYsly_Wo' , title: 'Артем Пилипец' 		, cat: { seo: 1 	, } 	, list: 'PL3MUz5vmQVkIMR4k2IGQlzsiLqDRB06WU', },
		{ href: '_owS95kJSoE' , title: 'Максим Набиуллин' 	, cat: { seo: 1 	, } 	, list: 'PL0JXWuret3E7LmnySrECq2j16EPBWVM01', },
	], 
},



{ 
	id: 'english', title: 'Английский', 
	nav: [ 
		{ id: 'all' 			, title: 'Все' 			, },
		{ id: 'bebris_1' 		, title: 'А.Бебрис-1' 	, },
		{ id: 'bebris_2' 		, title: 'А.Бебрис-2' 	, },
		{ id: 'polyglot' 		, title: 'Полиглот' 	, },


		//{ id: '' 	, title: '' 		, },
	],
	arr: [

		{ href: 'Hp9wUEDasY4' , title: 'Теория (1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'jMCOyUgKhqU' , title: 'Практика (1.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'nXI9CN5a6ew' , title: 'Теория (2)' 			, cat: { bebris_1: 1 , } , },
		{ href: '7MnnYT9hWLg' , title: 'Практика (2.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'GCNEqFJM3GA' , title: 'Теория (3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'zc-4grfULhg' , title: 'Практика (3.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: '1nkoP6NosxU' , title: 'Теория (4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'oDbDuu17p7I' , title: 'Практика (4.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'nPXmJZx60K0' , title: 'Повторение (5)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'EJEKg2lkjW4' , title: 'КР 1 (5.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'oo6HUQd7fnE' , title: 'КР 2 (5.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'arCOcpSlsNE' , title: 'КР 3 (5.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'g54X7P-QMQ8' , title: 'Теория (6)' 			, cat: { bebris_1: 1 , } , },
		{ href: '3rBR7sKA4Eo' , title: 'Практика (6.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: '006VR_z3iYc' , title: 'Теория (7)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'b34X_3Nb-cE' , title: 'Практика (7.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: '8O2JICbDthQ' , title: 'Теория (8)' 			, cat: { bebris_1: 1 , } , },
		{ href: '-bdj0TgQCp4' , title: 'Практика (8.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: '82Z289SJSYA' , title: 'Теория (9)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'eIn2z55aSXg' , title: 'Практика (9.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'RQL8lICKsiA' , title: 'Теория (10)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'UcVJ7O10Ii8' , title: 'Практика (10.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'IsKSfWnkqiE' , title: 'Повторение 1 (11)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'RT7Iy7OZcos' , title: 'Повторение 2 (12)' 		, cat: { bebris_1: 1 , } , },
		{ href: '3k4L-qZs-_0' , title: 'Повторение 3 (13)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'MoVZGyxjnbg' , title: 'КР 1 (11.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Q6YEVnihBZU' , title: 'КР 2 (11.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'RIBID1WoIJA' , title: 'КР 3 (12.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: '97U3119r4Yk' , title: 'КР 4 (12.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'lK5fC6J7Jmk' , title: 'КР 5 (13.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: '-YhoaobFcqQ' , title: 'КР 6 (13.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 's2mDQEUY9ac' , title: 'Теория (14)' 			, cat: { bebris_1: 1 , } , },
		{ href: '5Hqg_P_eVJM' , title: 'Практика (14.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'IlSNy49QRm0' , title: 'Теория (15)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'UnhchN3am_c' , title: 'Практика (15.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: '2Yr6DvVRe-I' , title: 'Теория (16)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'G0EW2yN7j2g' , title: 'Практика (16.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: '_z9rz35ks2A' , title: 'Теория (17)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'TG5x5z5wGlk' , title: 'Теория (17.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'a7FIdktMwS8' , title: 'Теория (18)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'p-M1hskVits' , title: 'Практика (18.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: '56PQdieS8ZA' , title: 'Практика (18.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'AcLZcx9p5-E' , title: 'Теория (19)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Y9BTiMV7hPQ' , title: 'Практика (19.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'AdJDHYwz1_8' , title: 'Практика (19.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: '88QDbO4V2t0' , title: 'Теория (20)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'LEdnUTNQloI' , title: 'Практика (20.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'mfsalx6Nojs' , title: 'Повторение (21)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'EBBl1Y4iioA' , title: 'СР 1 (21.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'jMG8S9odePg' , title: 'СР 2 (21.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'WDYiEj2FA4g' , title: 'Повторение 1 (22)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'sCoR5lhOEJU' , title: 'Повторение 2 (23)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'SAUuT11ya5U' , title: 'Повторение 3 (24)' 		, cat: { bebris_1: 1 , } , },
		{ href: '_EGF9l9808w' , title: 'Повторение 4 (25)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'zbgF335KN8U' , title: 'КР 1 (22.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'xioVluBC0Ac' , title: 'КР 2 (22.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'AL-R4Uc7X14' , title: 'КР 3 (22.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'kEktEl6uj5s' , title: 'КР 4 (23.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'bQ9l7m7KUYk' , title: 'КР 5 (23.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'StAi1-HOAoQ' , title: 'КР 6 (23.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'qQGKsAeF9fI' , title: 'КР 7 (24.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'mAI4tMAZtXg' , title: 'КР 8 (24.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Oahp_V3N8Ls' , title: 'КР 9 (24.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'gC0GGhMGpA4' , title: 'КР 10 (25.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'sctMdg9ISp0' , title: 'КР 11 (25.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Eg9ajlwjvHI' , title: 'КР 12 (25.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'CY3wNk3_Rnw' , title: 'КР 13 (25.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Evv2O-6K0pM' , title: 'КР 14 (25.5)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'bB4K-WblSIk' , title: 'Теория (26)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Dym4N0hq15Q' , title: 'Практика (26.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'EmmoAPtgllA' , title: 'Теория (27)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'dGBzXBiuW8Y' , title: 'Практика (27.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'gPRaahcizTo' , title: 'Практика (27.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: '3pvq0lHmLXM' , title: 'Теория (28)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'CLBV1M0lYR4' , title: 'Практика (28.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'lHGmAktrPd4' , title: 'Теория (29)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'bU8V9lQPr3s' , title: 'Практика (29.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'PX3dPCdSTgY' , title: 'Практика (29.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: '9omB2YuL1Z8' , title: 'Теория (30)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'rN-IiOXyCTo' , title: 'Практика (30.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'yiReY7BothA' , title: 'Практика (30.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'mRQMPhB6c_Y' , title: 'Теория (31)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'ieTxQ0bvSuQ' , title: 'Практика (31.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'OHIMU1eRgrI' , title: 'Практика (31.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'TLJa6rBI6pE' , title: 'Теория (32)' 			, cat: { bebris_1: 1 , } , },
		{ href: '0fwM9aTQK_c' , title: 'Практика (32.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'jylKH_EKUMk' , title: 'Практика (32.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'sQ6HMW37Xh4' , title: 'Теория (33)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'D5Et9y_L_70' , title: 'Практика (33.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'XXPzbMBNzrY' , title: 'Теория (34)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'tdNnrY5vj1M' , title: 'СР 1 (34.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'vEs5dg-ugzY' , title: 'СР 1 (34.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Lm2qTz13GYQ' , title: 'Повторение 1 (35)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'nprgm-55chU' , title: 'Повторение 2 (36)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'AKBQ7NFkR80' , title: 'Повторение 3 (37)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'AV2-0chexqQ' , title: 'Повторение 4 (38)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'gDcvt3huH_g' , title: 'КР 1 (35.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'UP_TH99hZYg' , title: 'КР 2 (35.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: '8YFu9R9MMxg' , title: 'КР 3 (35.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'ABdABo27F8c' , title: 'КР 4 (35.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: '2GRJq4Y9gOo' , title: 'КР 5 (36.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'G95E7rjSvSQ' , title: 'КР 6 (36.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'AZNVY021qTo' , title: 'КР 7 (36.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: '-vKhj6LHVlQ' , title: 'КР 8 (36.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: '3mu_hLjqK7k' , title: 'КР 9 (37.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'nT_UcGw4vXI' , title: 'КР 10 (37.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: '0cnIEqI_J1w' , title: 'КР 11 (37.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: '3-WJu7E3tzo' , title: 'КР 12 (37.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'T8VF9d_V0eU' , title: 'КР 13 (38.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: '5L2YlNDIxko' , title: 'КР 14 (38.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'plVpgXzQ8a0' , title: 'КР 15 (38.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'hXILgGjXZ_k' , title: 'КР 16 (38.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 's8VJa3pR9sc' , title: 'Повторение 1 (39)' 		, cat: { bebris_1: 1 , } , }, 
		{ href: 'Yi0-18Md5_A' , title: 'Повторение 2 (40)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'f0SNtoGIuTY' , title: 'Повторение 3 (41)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'u_xbxenErqg' , title: 'Повторение 4 (42)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'gBZZJf-ErmA' , title: 'Повторение 5 (43)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'dpKDAuHpqeI' , title: 'Повторение 6 (44)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'OSvs4Lxn9j4' , title: 'Повторение 7 (45)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'Ap9QwMbNTEY' , title: 'Повторение 8 (46)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'rOAwk7uFqQQ' , title: 'Повторение 9 (47)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'vQ1UIDyBXbc' , title: 'Повторение 10 (48)' 	, cat: { bebris_1: 1 , } , },
		{ href: '-CYHEQ0eEMU' , title: 'КР 1 (39.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: '7bG7cTT0IzU' , title: 'КР 2 (39.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'YB4IelrxmHc' , title: 'КР 3 (39.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'kHNhU578-lM' , title: 'КР 4 (39.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: '6m-ocUq9zR4' , title: 'КР 5 (40.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'S4Wpq9CWGjk' , title: 'КР 6 (40.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Yj51yPUqMV4' , title: 'КР 7 (40.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'HAIKpM6VBaM' , title: 'КР 8 (40.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'A-CyOKoclZU' , title: 'КР 9 (41.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'PGGx_4ZbVaU' , title: 'КР 10 (41.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: '3ZwxdDNx27E' , title: 'КР 11 (41.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'nUOOmP4-L_A' , title: 'КР 12 (41.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'TCgVgHvW7DU' , title: 'КР 13 (42.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'sxtn_ZfQtbo' , title: 'КР 14 (42.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'ZsyH3ICruoA' , title: 'КР 15 (42.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'GS_ZzJaOmkE' , title: 'КР 16 (42.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'XJKCTHDZuEA' , title: 'КР 17 (43.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'XlNhgJ2qNeI' , title: 'КР 18 (43.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'f87v-f7lMVk' , title: 'КР 19 (43.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'jo7r258hu-8' , title: 'КР 20 (43.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'nJasm5s6cqc' , title: 'КР 21 (44.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'jNopAfD52XQ' , title: 'КР 22 (44.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 's877Vu-3rLk' , title: 'КР 23 (44.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'JIDZi-Esj8E' , title: 'КР 24 (44.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'hh-BA0eJys8' , title: 'КР 25 (45.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'm28TJDVImSU' , title: 'КР 26 (45.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: '0cyjjJEgFs8' , title: 'КР 27 (45.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'k_0rz19K31U' , title: 'КР 28 (45.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'hFg-X5_pcUM' , title: 'КР 29 (46.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'li27_C1zaH0' , title: 'КР 30 (46.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'v0c9UvYUBA8' , title: 'КР 31 (46.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'qiPBN6xgBjY' , title: 'КР 32 (46.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'iboHO75yMDg' , title: 'КР 33 (47.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'o7L1WxjJWRA' , title: 'КР 34 (47.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'BbX1UGn7BCo' , title: 'КР 35 (47.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: '5Y4jvbrmTZw' , title: 'КР 36 (47.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'bKmDKgMThWQ' , title: 'КР 37 (48.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'QIiMD8uRgSE' , title: 'КР 38 (48.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'wZ8BoZWxBTU' , title: 'КР 39 (48.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'VGUuI4Q2wH0' , title: 'КР 40 (48.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: '4Tt_XQw5Q9k' , title: 'Теория (49)' 			, cat: { bebris_1: 1 , } , },
		{ href: '4SdYPqvsbps' , title: 'Практика (49.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'JQqGSOoY6oE' , title: 'Теория (50)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'laXccxIByaU' , title: 'Практика (50.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'aWv9LlHCdhQ' , title: 'Теория (51)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'srdrcbUnS30' , title: 'Практика (51.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'nCbGwDXql3k' , title: 'Теория (52)' 			, cat: { bebris_1: 1 , } , },
		{ href: '-9-EfWeOi5w' , title: 'Практика (52.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'H2WstZIjwDw' , title: 'Теория (53)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'pTsh_NdOOLk' , title: 'Практика (53.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'eS6-1Ajt4go' , title: 'Теория (54)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'CMN9Xh5A4Es' , title: 'Практика (54.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'TNpl9twtT_Q' , title: 'Теория (55)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'PHCpV27Is4o' , title: 'Практика (55.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'TmdM0stXU7s' , title: 'Теория (56)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'iXCVWYVXp1s' , title: 'Практика (56.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'dreip9BSJg4' , title: 'Повторение 1 (57)' 		, cat: { bebris_1: 1 , } , },
		{ href: '32OxKF-FoNw' , title: 'Повторение 2 (58)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'hUWh15C6Pqk' , title: 'Повторение 3 (59)' 		, cat: { bebris_1: 1 , } , },
		{ href: '2bsDP-r-RGk' , title: 'Повторение 4 (60)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'Brq2IJQBygo' , title: 'Повторение 5 (61)' 		, cat: { bebris_1: 1 , } , },
		{ href: '5dBY5fTdMhc' , title: 'Повторение 6 (62)' 		, cat: { bebris_1: 1 , } , },
		{ href: '136_ZkikgA4' , title: 'Повторение 7 (63)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'i02wmHzONyM' , title: 'КР 1 (57.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'm83_5eJVrZ8' , title: 'КР 2 (57.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'LQfINbItH9k' , title: 'КР 3 (57.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'xFr1saVX08k' , title: 'КР 4 (58.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: '9axA1-SSmBY' , title: 'КР 5 (58.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'TRBGSbXkoB0' , title: 'КР 6 (58.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'b2iXU_Ok4uA' , title: 'КР 7 (59.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'VWgSuLIBOOs' , title: 'КР 8 (59.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: '5cSUAbHUY90' , title: 'КР 9 (59.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'QLqskyVhcZc' , title: 'КР 10 (60.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: '7qEaOGcElKc' , title: 'КР 11 (60.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'GbQBotYQ1aw' , title: 'КР 12 (60.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'cvUNv-vrmLs' , title: 'КР 13 (61.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'rvQ2yA3epg4' , title: 'КР 14 (61.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'DEiNQ2-leHU' , title: 'КР 15 (61.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Tzy8aMcI1xc' , title: 'КР 16 (62.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'WnMFfK7EXVU' , title: 'КР 17 (62.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'KVDh4gy86PQ' , title: 'КР 18 (62.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'APMyOPzoqcQ' , title: 'КР 19 (63.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'JdnjkyLtZDw' , title: 'КР 20 (63.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'RWRV45-9t-g' , title: 'КР 21 (63.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: '-EpxMKCuyn0' , title: 'КР 22 (63.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'NuCN0w01EdE' , title: 'КР 23 (63.5)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'oE0epGjQEyc' , title: 'Теория (64)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'FPqjEaeN72U' , title: 'Практика (64.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'wnGpdPYIeoI' , title: 'Теория (65)' 			, cat: { bebris_1: 1 , } , },
		{ href: '1w6Bpg6QZK4' , title: 'Практика (65.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'EIzfWhKDqis' , title: 'Теория (66)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'yRtc1wJUjBU' , title: 'Практика (66.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'DhMK1F2uW1Q' , title: 'Теория (67)' 			, cat: { bebris_1: 1 , } , },
		{ href: '9nfVbD7cXXE' , title: 'Практика (67.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'rlhuGvO_WBI' , title: 'Теория (68)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Eha1evK2prU' , title: 'Практика (68.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'XhOp3G3LdzI' , title: 'Теория (69)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'tvNxqg697WY' , title: 'Практика (69.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'R0xhMzzIFQo' , title: 'Теория (70)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'i2mR6z1pF0A' , title: 'Практика (70.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'eSt2lMEhR-8' , title: 'Теория (71)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'WdFtto8aL-8' , title: 'Практика (71.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'ih_p3n6fT68' , title: 'Теория (72)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'jK_RdO-iSpo' , title: 'Практика (72.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'PLxFmdAyIaY' , title: 'Повторение 1 (73)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'ygOV2IfxnkM' , title: 'Повторение 2 (74)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'cxfKgU1esLw' , title: 'Повторение 3 (75)' 		, cat: { bebris_1: 1 , } , },
		{ href: '_ojiHIwALuo' , title: 'Повторение 4 (76)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'LDcxu9L9luo' , title: 'Повторение 5 (77)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'wkA7J_CQ_EE' , title: 'Повторение 6 (78)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'Cax716pGwDc' , title: 'КР 1 (73.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'DsTjMr0W7WI' , title: 'КР 2 (73.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'ICcpRiSOzuo' , title: 'КР 3 (73.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: '6avV1NTqQBM' , title: 'КР 4 (74.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'TMzDvx06QRA' , title: 'КР 5 (74.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'jD5SXLTMRVE' , title: 'КР 6 (74.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'xJmIApKFrcw' , title: 'КР 7 (75.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'NWKAg_7SV1U' , title: 'КР 8 (75.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'BQ5Mpn1nY5o' , title: 'КР 9 (75.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'r3Wq4n8i2q0' , title: 'КР 10 (76.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'PMi8eweYTzw' , title: 'КР 11 (76.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'keBNTNroMDg' , title: 'КР 12 (76.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'PgAtqbJkFko' , title: 'КР 13 (77.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'O3QW86TkdXg' , title: 'КР 14 (77.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'pPni2qi-86g' , title: 'КР 15 (77.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'D8Gl28O9dK4' , title: 'КР 16 (78.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: '6LVEgkqxEbI' , title: 'КР 17 (78.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'ZTAuacpc5Q8' , title: 'КР 18 (78.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'oAziZ0eLy68' , title: 'Теория (79)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'tf01dDZA4PI' , title: 'Практика (79.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'sxmNTfmhs9k' , title: 'Теория (80)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'PLKWjbBC2FI' , title: 'Практика (80.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'M6eOW9wdWDU' , title: 'Теория (81)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'mCrk6vVR78M' , title: 'Практика (81.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'RsJ0IsBjcsE' , title: 'Теория (82)' 			, cat: { bebris_1: 1 , } , },
		{ href: '731rgD7zI0g' , title: 'Практика (82.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: '8ZG2wN_mIw0' , title: 'Теория (83)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Tnyyr_ia-8A' , title: 'Практика (83.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'WjA4X6mPnZE' , title: 'Теория (84)' 			, cat: { bebris_1: 1 , } , },
		{ href: '1JGOLwC04y0' , title: 'Практика (84.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'Dtws-e2jZzI' , title: 'Теория (85)' 			, cat: { bebris_1: 1 , } , },
		{ href: '5BvOjR_7D7I' , title: 'Практика (85.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'r95WvAeOuLg' , title: 'Теория (86)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'x_NjsWK0Mmo' , title: 'Практика (86.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'ZaFJwEvUmWQ' , title: 'Теория (87)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'lbnQsMw32pc' , title: 'Практика (87.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'xX5_E8M6zs4' , title: 'Теория (88)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'DxeJszUYnJg' , title: 'Практика (88.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'BSmoM5QeY7g' , title: 'Повторение 1 (89)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'T4VCeebMWLI' , title: 'Повторение 2 (90)' 		, cat: { bebris_1: 1 , } , },
		{ href: 't1j3HIp5YWo' , title: 'Повторение 3 (91)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'W8xGSdJ98N8' , title: 'Повторение 4 (92)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'o9uWYx6ugNU' , title: 'Повторение 5 (93)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'AOI0s9UAln4' , title: 'КР 1 (89.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'W9rHI-XZKFU' , title: 'КР 2 (89.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: '3sibekjyfTo' , title: 'КР 3 (89.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'YEkkvZwDvZs' , title: 'КР 4 (90.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: '-3sDRT9FYmc' , title: 'КР 5 (90.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'zq9_Lex0v-o' , title: 'КР 6 (90.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'dTPHPvbbFLA' , title: 'КР 7 (91.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'dBSgsFaLm6w' , title: 'КР 8 (91.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'cMoCV10zfWA' , title: 'КР 9 (91.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'cR6dyfFlYo4' , title: 'КР 10 (92.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'OIdZmkVk5_E' , title: 'КР 11 (92.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'K1FVoC6x3Xs' , title: 'КР 12 (92.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'tVDdV5IztoQ' , title: 'КР 13 (93.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'c7H2hyYacmQ' , title: 'КР 14 (93.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'AxKJWgpLQ7M' , title: 'КР 15 (93.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'g8ZbFeoUhb0' , title: 'Теория (94)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'pIR__InufC0' , title: 'Практика (94.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'MzvC6xfF4i0' , title: 'Теория (95)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'g6dNKBrYO5k' , title: 'Практика (95.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'IJxWAVRX0Dw' , title: 'Теория (96)' 			, cat: { bebris_1: 1 , } , },
		{ href: '6QzgVSAHyXU' , title: 'Практика (96.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: '073mRqaAExA' , title: 'Теория (97)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'I_hiheUCiLI' , title: 'Практика (97.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'oakvMzl5AXo' , title: 'Теория (98)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'NgOQYjreTfo' , title: 'Практика (98.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'GHSqzsRcMF8' , title: 'Теория (99)' 			, cat: { bebris_1: 1 , } , },
		{ href: '7bqbYzZyhas' , title: 'Практика (99.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'ZHzzf7xPdNA' , title: 'Теория (100)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'bhXwThsxaL8' , title: 'Практика (100.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'tJQ-vMO-qV8' , title: 'Теория (101)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'BAKNWnf0Tbs' , title: 'Практика (101.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'p8ycpsyRp0M' , title: 'Теория (102)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'w1_tckez0sc' , title: 'Практика (102.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'Qp42X6-4S9w' , title: 'Теория (103)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'b_2x1_doBCA' , title: 'Практика (103.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'Ol4La1-di8o' , title: 'Повторение 1 (104)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'JNRpC7pqVMo' , title: 'Повторение 2 (105)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'T2rNu1NNnzU' , title: 'Повторение 3 (106)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'mdt3OoadgRs' , title: 'Повторение 4 (107)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'Q2TMtvp57GE' , title: 'КР 1 (104.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'pnBBf7TE0HQ' , title: 'КР 2 (104.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'zcJN9w3pYlg' , title: 'КР 3 (104.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: '_yTuwFkdocA' , title: 'КР 4 (105.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'AaYJloYUGAw' , title: 'КР 5 (105.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'lx3yZMxe3SM' , title: 'КР 6 (105.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'o-T427p-Uoc' , title: 'КР 7 (106.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'h6tN8Pvwijk' , title: 'КР 8 (106.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'tqA4MSVWu3c' , title: 'КР 9 (106.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'rQDhfT4dDes' , title: 'КР 10 (107.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: '7BryoZv_DUk' , title: 'КР 11 (107.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'FQBPnHme54s' , title: 'КР 12 (107.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'HAT-BbvXUxo' , title: 'Повторение 1 (108)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'WRP5KyGofUk' , title: 'Повторение 2 (109)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'JcwsMnM5fO4' , title: 'Повторение 3 (110)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'A2xZJAJFxWo' , title: 'Повторение 4 (111)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'KLLeabGsXy4' , title: 'Повторение 5 (112)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'NuK_sts30Yc' , title: 'Повторение 6 (113)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'aC2lmHhiRfI' , title: 'Повторение 7 (114)' 	, cat: { bebris_1: 1 , } , },
		{ href: '1TZBJ7yvDSQ' , title: 'Повторение 8 (115)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'ejGM6xAXcQs' , title: 'Повторение 9 (116)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'QPloZgDEEcc' , title: 'Повторение 10 (117)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'Po2cimRUEjM' , title: 'Повторение 11 (118)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'ddSmCqQm7-4' , title: 'Повторение 12 (119)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'Z6854VPZKiM' , title: 'Повторение 13 (120)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'ntgd4E3fh3Y' , title: 'Повторение 14 (121)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'PzXognTixAQ' , title: 'Повторение 15 (122)' 	, cat: { bebris_1: 1 , } , },
		{ href: '2LZl-39wdRE' , title: 'Повторение 16 (123)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'rlAme9b-ZmQ' , title: 'Повторение 17 (124)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'zL5lzmIyiOE' , title: 'Повторение 18 (125)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'Sc3gG0bcZfg' , title: 'Повторение 19 (126)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'LwkS_3gQcrM' , title: 'Повторение 20 (127)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'p_tDzezr7xo' , title: 'Повторение 21 (128)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'F5ThbpC2nx0' , title: 'Повторение 22 (129)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'L3hzTRiAn7E' , title: 'Повторение 23 (130)' 	, cat: { bebris_1: 1 , } , },
		{ href: '6PprxkhsNJE' , title: 'Повторение 24 (131)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'CdrBvqZRuoQ' , title: 'Повторение 25 (132)' 	, cat: { bebris_1: 1 , } , },
		{ href: 'MwUir_R4FOA' , title: 'КР 1 (108.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'g81K9w2xNcI' , title: 'КР 2 (108.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: '9qwiwUTofAQ' , title: 'КР 3 (108.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'snTGZrEUkDU' , title: 'КР 4 (108.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'q4son28KjDI' , title: 'КР 5 (108.5)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'LrhPl5Xxj0Q' , title: 'КР 6 (108.6)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Qo4ENziCAdc' , title: 'КР 7 (108.7)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'T9nePm4hsF0' , title: 'КР 8 (108.8)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'nIPrrbk5GWQ' , title: 'КР 9 (109.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'hWwo3Tmmxeg' , title: 'КР 10 (109.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: '27Du3qgrqxk' , title: 'КР 11 (109.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'j_vgjs7Bnoo' , title: 'КР 12 (109.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: '6kxLGpLfaLo' , title: 'КР 13 (109.5)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'zmGV8G_PnDI' , title: 'КР 14 (109.6)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'X5L7CFLoFxw' , title: 'КР 15 (109.7)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'kqeX1QOtedo' , title: 'КР 16 (109.8)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Ro1PuzJf8VQ' , title: 'КР 17 (110.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'FgKyKab4EGA' , title: 'КР 18 (110.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'xU2QcwyuD3I' , title: 'КР 19 (110.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'yGGrgDH7Nbo' , title: 'КР 20 (110.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: '1NTD2v4k7hc' , title: 'КР 21 (110.5)' 			, cat: { bebris_1: 1 , } , },
		{ href: '6wID4gvVbT8' , title: 'КР 22 (110.6)' 			, cat: { bebris_1: 1 , } , },
		{ href: '7y_vfQecAuk' , title: 'КР 23 (110.7)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'n_4kinKzW5A' , title: 'КР 24 (110.8)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'UA5Hitp7FFE' , title: 'КР 25 (111.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: '3qMtSYSVdeg' , title: 'КР 26 (111.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: '5jsl0e5_leM' , title: 'КР 27 (111.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'y6eq69_IVNU' , title: 'КР 28 (111.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: '3fVNeq4rLNU' , title: 'КР 29 (111.5)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'TPR8Yu5yJig' , title: 'КР 30 (111.6)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Rh_FkLO3qNg' , title: 'КР 31 (111.7)' 			, cat: { bebris_1: 1 , } , },
		{ href: '3U-1_JDhXSU' , title: 'КР 32 (111.8)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'wVF6-QADNjQ' , title: 'КР 33 (112.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'p-QlZFXASds' , title: 'КР 34 (112.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: '6rJtriNBfnw' , title: 'КР 35 (112.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'ymrGHDhOilA' , title: 'КР 36 (112.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Ra5158tpwGk' , title: 'КР 37 (112.5)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'A80meqkP3Aw' , title: 'КР 38 (112.6)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'OdWXqb7zLPM' , title: 'КР 39 (112.7)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'YLlqz8qYKPo' , title: 'КР 40 (112.8)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'FSxy-DwHOxE' , title: 'КР 41 (113.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'BmXo0jyn8YQ' , title: 'КР 42 (113.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'SGw3oxIS_wE' , title: 'КР 43 (113.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'YZZ9m-BhySc' , title: 'КР 44 (113.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'n9hm_HJkW-Q' , title: 'КР 45 (113.5)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'fOtocCMsmcU' , title: 'КР 46 (113.6)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'U1tR7bW9eEA' , title: 'КР 47 (113.7)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'ZMKdolPRZKQ' , title: 'КР 48 (113.8)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'uXVPaRKvc88' , title: 'КР 49 (114.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'NCtnGRm7hTs' , title: 'КР 50 (114.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'nGCP5gpmMVU' , title: 'КР 51 (114.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'gfbI2qacQfQ' , title: 'КР 52 (114.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Jfc80Nhs-B0' , title: 'КР 53 (114.5)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'lJsjFNWdpoA' , title: 'КР 54 (114.6)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'F_V2wZy03M0' , title: 'КР 55 (114.7)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'r0LdhYrOppY' , title: 'КР 56 (114.8)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'APFFTnNDHjI' , title: 'КР 57 (115.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: '_nJe12byVYE' , title: 'КР 58 (115.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'dupji62a-lg' , title: 'КР 59 (115.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'rfISCgZxhHY' , title: 'КР 60 (115.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: '2MbDs6pH4vw' , title: 'КР 61 (115.5)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'RK1LGCh4Teo' , title: 'КР 62 (115.6)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'NwQAfumlPIo' , title: 'КР 63 (115.7)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'YXcCn7h1yoQ' , title: 'КР 64 (115.8)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'nAxyuH3ZVXo' , title: 'КР 65 (116.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'ktDuSl7a8N0' , title: 'КР 66 (116.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: '70b8tQFfwD4' , title: 'КР 67 (116.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'lqe2Pv6TyyA' , title: 'КР 68 (116.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'FyjYs6WtYh8' , title: 'КР 69 (116.5)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'EYllR5Yhltw' , title: 'КР 70 (116.6)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'sqC7Hqj7yYE' , title: 'КР 71 (116.7)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'pgiIxD9OQx8' , title: 'КР 72 (116.8)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'UVDnhj-jZl0' , title: 'КР 73 (117.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: '6bjhoBP4J1M' , title: 'КР 74 (117.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'aCwdw0zLJcE' , title: 'КР 75 (117.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: '5RP_M9MTnuM' , title: 'КР 76 (117.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'yQUUvUSAElw' , title: 'КР 77 (117.5)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'KiSmrrC1-dQ' , title: 'КР 78 (117.6)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'WQDF-ZisVgw' , title: 'КР 79 (117.7)' 			, cat: { bebris_1: 1 , } , },
		{ href: '-oTiq1rsDB4' , title: 'КР 80 (117.8)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'uZ1Z7VuTym0' , title: 'КР 81 (118.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'cyiJ0Xe1KxU' , title: 'КР 82 (118.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: '7d54rOnrT-I' , title: 'КР 83 (118.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: '5l83WWxmWt0' , title: 'КР 84 (118.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'HoZhhvikKQI' , title: 'КР 85 (118.5)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'o716N4IQ99w' , title: 'КР 86 (118.6)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Bl7XGRuqLv4' , title: 'КР 87 (118.7)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'FjKl0v7VhpA' , title: 'КР 88 (118.8)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'Uk3veZlY_mo' , title: 'КР 89 (119.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'WNRhpOtMcQk' , title: 'КР 90 (119.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'SOhkhu04LGA' , title: 'КР 91 (119.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'FQ-6RN9I8SQ' , title: 'КР 92 (119.4)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'GjENcXRhcks' , title: 'КР 93 (119.5)' 			, cat: { bebris_1: 1 , } , },
		{ href: '06gEEON9jGY' , title: 'КР 94 (119.6)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'noed-Tc_zxM' , title: 'КР 95 (119.7)' 			, cat: { bebris_1: 1 , } , },
		{ href: '3E6pUJz76As' , title: 'КР 96 (119.8)' 			, cat: { bebris_1: 1 , } , },
		{ href: '34oIKR_q9YY' , title: 'КР 97 (120.1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'sRiuHFCeens' , title: 'КР 98 (120.2)' 			, cat: { bebris_1: 1 , } , },
		{ href: '-nETw_6J2kI' , title: 'КР 99 (120.3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'aPId0iIzaJU' , title: 'КР 100 (120.4)' 		, cat: { bebris_1: 1 , } , },
		{ href: '_QHmNFSHj9c' , title: 'КР 101 (120.5)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'jd0PRZEhuqQ' , title: 'КР 102 (120.6)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'GuXiDytJc-8' , title: 'КР 103 (120.7)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'gEYLyroDnXo' , title: 'КР 104 (120.8)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'uurmxVxY0jE' , title: 'КР 105 (121.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'KSVSDbxVvJQ' , title: 'КР 106 (121.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'zvLrxzdVh7Y' , title: 'КР 107 (121.3)' 		, cat: { bebris_1: 1 , } , },
		{ href: '9TUdKHAHAlI' , title: 'КР 108 (121.4)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'CDOrBnzGHFk' , title: 'КР 109 (121.5)' 		, cat: { bebris_1: 1 , } , },
		{ href: '2G062iRKu7Q' , title: 'КР 110 (121.6)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'PPZmie7ULZo' , title: 'КР 111 (121.7)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'ZOJ3zWrITF0' , title: 'КР 112 (121.8)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'fx1FmtzxfqQ' , title: 'КР 113 (122.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'apNpUMriBsQ' , title: 'КР 114 (122.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: '4QhrL9W0Ifc' , title: 'КР 115 (122.3)' 		, cat: { bebris_1: 1 , } , },
		{ href: '0dO8RzM7Rkw' , title: 'КР 116 (122.4)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'hXYieVvrWDk' , title: 'КР 117 (122.5)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'xIs3eJ3SkTM' , title: 'КР 118 (122.6)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'p6rJpxOZarc' , title: 'КР 119 (122.7)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'G41yyzJnxkM' , title: 'КР 120 (122.8)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'tDCeUVdsz-g' , title: 'КР 121 (123.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: '5Waw6HKT2aU' , title: 'КР 122 (123.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'uIH2CDspjLA' , title: 'КР 123 (123.3)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'qsyaY0lj3ws' , title: 'КР 124 (123.4)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'HaIA3GOufys' , title: 'КР 125 (123.5)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'Eg-oDKsMJbI' , title: 'КР 126 (123.6)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'PGMtBTyaPMo' , title: 'КР 127 (123.7)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'wcX1CVsXxdY' , title: 'КР 128 (123.8)' 		, cat: { bebris_1: 1 , } , },
		{ href: '4cFViiBF8MA' , title: 'КР 129 (124.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'MguS0fCnvuI' , title: 'КР 130 (124.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: '6-EflOBLhqY' , title: 'КР 131 (124.3)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'Ragujw43ehI' , title: 'КР 132 (124.4)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'itteJagyqWg' , title: 'КР 133 (124.5)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'ltPbjDUaFDg' , title: 'КР 134 (124.6)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'Jwe1AKBU8UI' , title: 'КР 135 (124.7)' 		, cat: { bebris_1: 1 , } , },
		{ href: '32ZCfCLkrLw' , title: 'КР 136 (124.8)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'ScvANI4NWXM' , title: 'КР 137 (125.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'kSyo010WrrQ' , title: 'КР 138 (125.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: '95CpA8mMj1s' , title: 'КР 139 (125.3)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'aU4MK4QQ9YM' , title: 'КР 140 (125.4)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'qygGrWcgqpo' , title: 'КР 141 (125.5)' 		, cat: { bebris_1: 1 , } , },
		{ href: '8ox0UhMOnDk' , title: 'КР 142 (125.6)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'BWxDnGrK488' , title: 'КР 143 (125.7)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'NtXkuTPoGyc' , title: 'КР 144 (125.8)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'turqXrQvQzk' , title: 'КР 145 (126.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'v7ADfztH-nc' , title: 'КР 146 (126.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: '6Hxsa-b5RuE' , title: 'КР 147 (126.3)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'KkFx3KIVKN8' , title: 'КР 148 (126.4)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'ws1ohN6WH-k' , title: 'КР 149 (126.5)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'MvZHWsxLT8M' , title: 'КР 150 (126.6)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'W3oaRNr_5KM' , title: 'КР 151 (126.7)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'wsI9J7WBYuQ' , title: 'КР 152 (126.8)' 		, cat: { bebris_1: 1 , } , },
		{ href: '2glcsYdj8h4' , title: 'КР 153 (127.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'ivVEnlbkLj4' , title: 'КР 154 (127.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: '1RbfqaILfj0' , title: 'КР 155 (127.3)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'CmNH-Dqwjmg' , title: 'КР 156 (127.4)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'IL7qCBPO_XE' , title: 'КР 157 (127.5)' 		, cat: { bebris_1: 1 , } , },
		{ href: '93aIqeMI1rM' , title: 'КР 158 (127.6)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'ox-JlVVXBSM' , title: 'КР 159 (127.7)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'WuH0fCSRIJk' , title: 'КР 160 (127.8)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'THlAxCxe_CY' , title: 'КР 161 (128.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'PbixHGu7txo' , title: 'КР 162 (128.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'TLrH9zKKV7Y' , title: 'КР 163 (128.3)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'UdjaUWINTs0' , title: 'КР 164 (128.4)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'c21eUvlBoJs' , title: 'КР 165 (128.5)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'Etf-OC8qNSU' , title: 'КР 166 (128.6)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'aFiq5aELEmo' , title: 'КР 167 (128.7)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'QySO46zukgs' , title: 'КР 168 (128.8)' 		, cat: { bebris_1: 1 , } , },
		{ href: '-ijzs0M9eQs' , title: 'КР 169 (129.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'Kh-EE8k9Vcc' , title: 'КР 170 (129.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: '9IiBOa6NbX0' , title: 'КР 171 (129.3)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'yv-6daS0DQU' , title: 'КР 172 (129.4)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'L69kp9OuBpA' , title: 'КР 173 (129.5)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'n2KsiNIH0n8' , title: 'КР 174 (129.6)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'dD-ftQ1eyTY' , title: 'КР 175 (129.7)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'vVcv6FR8g3w' , title: 'КР 176 (129.8)' 		, cat: { bebris_1: 1 , } , },
		{ href: '2aBdKgNdLFE' , title: 'КР 177 (130.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'RHFEz1EtwYQ' , title: 'КР 178 (130.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'ZarRSwMsS7c' , title: 'КР 179 (130.3)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'TQ1TDrCRMBU' , title: 'КР 180 (130.4)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'WbL3_mqC88Q' , title: 'КР 181 (130.5)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'cnSgfmkznSg' , title: 'КР 182 (130.6)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'IaEDFna_v9o' , title: 'КР 183 (130.7)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'LDhUF2C2H6s' , title: 'КР 184 (130.8)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'JPiGhlP8GwY' , title: 'КР 185 (131.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: '6exZ4o2dDS8' , title: 'КР 186 (131.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'ZizXm3aAaFA' , title: 'КР 187 (131.3)' 		, cat: { bebris_1: 1 , } , },
		{ href: '2SPGcm_eqFA' , title: 'КР 188 (131.4)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'D2am-xP36uw' , title: 'КР 189 (131.5)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'IVJQ8KFZLMY' , title: 'КР 190 (131.6)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'dsHUsKnWY70' , title: 'КР 191 (131.7)' 		, cat: { bebris_1: 1 , } , },
		{ href: '41I6kKb9a-U' , title: 'КР 192 (131.8)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'JW1xumAmjds' , title: 'КР 193 (132.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'bfr0Nw2X3Mw' , title: 'КР 194 (132.2)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'qWlW9a4uQvM' , title: 'КР 195 (132.3)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'Lk2aarosNQE' , title: 'КР 196 (132.4)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'RgfnPokf7wo' , title: 'КР 197 (132.5)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'xqxuisDZ-_c' , title: 'КР 198 (132.6)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'Je02SLS7vT4' , title: 'КР 199 (132.7)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'jJ8xmm6kO7c' , title: 'КР 200 (132.8)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'Hp9wUEDasY4' , title: 'Теория (1)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'jMCOyUgKhqU' , title: 'Практика (1.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'nXI9CN5a6ew' , title: 'Теория (2)' 			, cat: { bebris_1: 1 , } , },
		{ href: '7MnnYT9hWLg' , title: 'Практика (2.1)' 		, cat: { bebris_1: 1 , } , },
		{ href: 'GCNEqFJM3GA' , title: 'Теория (3)' 			, cat: { bebris_1: 1 , } , },
		{ href: 'zc-4grfULhg' , title: 'Практика (3.1)' 		, cat: { bebris_1: 1 , } , },

		{ href: '6Y-aBWo-xFk' , title: 'Урок 001' 				, cat: { bebris_2: 1 , } , },
		{ href: '7wN6Zi_KUE8' , title: 'Урок 002' 				, cat: { bebris_2: 1 , } , },
		{ href: '8AbGUAK9lFY' , title: 'Урок 003' 				, cat: { bebris_2: 1 , } , },
		{ href: 'wmx8-shCavQ' , title: 'Урок 004' 				, cat: { bebris_2: 1 , } , },
		{ href: 'b5p_jAGlS_U' , title: 'Урок 005' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Z3XpJfJbo5o' , title: 'Урок 006' 				, cat: { bebris_2: 1 , } , },
		{ href: 'mOy4ovI0uVA' , title: 'Урок 007' 				, cat: { bebris_2: 1 , } , },
		{ href: '627T-sjxHPY' , title: 'Урок 008' 				, cat: { bebris_2: 1 , } , },
		{ href: 'aWkbGnJek3I' , title: 'Урок 009' 				, cat: { bebris_2: 1 , } , },
		{ href: 'afvytX9f7Qc' , title: 'Урок 010' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Dt6YcGWfAq8' , title: 'Урок 011' 				, cat: { bebris_2: 1 , } , },
		{ href: '7RF7DDOP2Qo' , title: 'Урок 012' 				, cat: { bebris_2: 1 , } , },
		{ href: 'JGfjtkrkMqY' , title: 'Урок 013' 				, cat: { bebris_2: 1 , } , },
		{ href: 'zH89bfUT9ao' , title: 'Урок 014' 				, cat: { bebris_2: 1 , } , },
		{ href: '6-pJl799D7o' , title: 'Урок 015' 				, cat: { bebris_2: 1 , } , },
		{ href: 'VNoNT1ao4O0' , title: 'Урок 016' 				, cat: { bebris_2: 1 , } , },
		{ href: 'JIcqcosZBnw' , title: 'Урок 017' 				, cat: { bebris_2: 1 , } , },
		{ href: '3ziNb02rfMc' , title: 'Урок 018' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ILCnGPYI3OM' , title: 'Урок 019' 				, cat: { bebris_2: 1 , } , },
		{ href: 'djeXuK4rxj0' , title: 'Урок 020' 				, cat: { bebris_2: 1 , } , },
		{ href: 'VZ4sZGdG1L0' , title: 'Урок 021' 				, cat: { bebris_2: 1 , } , },
		{ href: 'TxGvu8K5Pew' , title: 'Урок 022' 				, cat: { bebris_2: 1 , } , },
		{ href: 'wU7qKMncMjY' , title: 'Урок 023' 				, cat: { bebris_2: 1 , } , },
		{ href: 'T6ZshkOzC20' , title: 'Урок 024' 				, cat: { bebris_2: 1 , } , },
		{ href: 'AvLgysmpY3w' , title: 'Урок 025' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ooke6PBRcfg' , title: 'Урок 026' 				, cat: { bebris_2: 1 , } , },
		{ href: '6fBL9ISy-co' , title: 'Урок 027' 				, cat: { bebris_2: 1 , } , },
		{ href: 'arjzyFCZJZk' , title: 'Урок 028' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ztw1hFitLPk' , title: 'Урок 029' 				, cat: { bebris_2: 1 , } , },
		{ href: 'KN65k9GPUoQ' , title: 'Урок 030' 				, cat: { bebris_2: 1 , } , },
		{ href: '0Ux7ikp5oU0' , title: 'Урок 031' 				, cat: { bebris_2: 1 , } , },
		{ href: '9Bt5UOSFDHM' , title: 'Урок 032' 				, cat: { bebris_2: 1 , } , },
		{ href: 'z7pX8XcW8E8' , title: 'Урок 033' 				, cat: { bebris_2: 1 , } , },
		{ href: 'OvtrUyXDpF4' , title: 'Урок 034' 				, cat: { bebris_2: 1 , } , },
		{ href: '2D-jdOX268Y' , title: 'Урок 035' 				, cat: { bebris_2: 1 , } , },
		{ href: 'nag2dLag6Mw' , title: 'Урок 036' 				, cat: { bebris_2: 1 , } , },
		{ href: 'XkVAGg0pU5g' , title: 'Урок 037' 				, cat: { bebris_2: 1 , } , },
		{ href: 'WoYnpIk0r2k' , title: 'Урок 038' 				, cat: { bebris_2: 1 , } , },
		{ href: 'pD3c0_f-_AE' , title: 'Урок 039' 				, cat: { bebris_2: 1 , } , },
		{ href: '7Gy00D597Eo' , title: 'Урок 040' 				, cat: { bebris_2: 1 , } , },
		{ href: '16L1uNFYPqs' , title: 'Урок 041' 				, cat: { bebris_2: 1 , } , },
		{ href: 'yaPZmOtXBlQ' , title: 'Урок 042' 				, cat: { bebris_2: 1 , } , },
		{ href: 'eCNc_I55vz8' , title: 'Урок 043' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Rw27Qs2JOYI' , title: 'Урок 044' 				, cat: { bebris_2: 1 , } , },
		{ href: '_xZWuUj1DOQ' , title: 'Урок 045' 				, cat: { bebris_2: 1 , } , },
		{ href: 'sABn1YHelKw' , title: 'Урок 046' 				, cat: { bebris_2: 1 , } , },
		{ href: '2o_zog6GIXw' , title: 'Урок 047' 				, cat: { bebris_2: 1 , } , },
		{ href: 'PRiE6DXD7lI' , title: 'Урок 048' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Q9G4lX4u1Zo' , title: 'Урок 049' 				, cat: { bebris_2: 1 , } , },
		{ href: '84-HjVxnaAU' , title: 'Урок 050' 				, cat: { bebris_2: 1 , } , },
		{ href: 'e9vi3UqDrNc' , title: 'Урок 051' 				, cat: { bebris_2: 1 , } , },
		{ href: '1OO2hNgMcck' , title: 'Урок 052' 				, cat: { bebris_2: 1 , } , },
		{ href: '0nQa3gwCzvc' , title: 'Урок 053' 				, cat: { bebris_2: 1 , } , },
		{ href: '4ag10gdRFbY' , title: 'Урок 054' 				, cat: { bebris_2: 1 , } , },
		{ href: '-XzHXkt67Lo' , title: 'Урок 055' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Nztz_W8aEw4' , title: 'Урок 056' 				, cat: { bebris_2: 1 , } , },
		{ href: 'XGpnERZ1zWc' , title: 'Урок 057' 				, cat: { bebris_2: 1 , } , },
		{ href: 'CqV0TBKQWEI' , title: 'Урок 058' 				, cat: { bebris_2: 1 , } , },
		{ href: 'CVZrDGyYhbA' , title: 'Урок 059' 				, cat: { bebris_2: 1 , } , },
		{ href: '5XFUwNLf7Uc' , title: 'Урок 060' 				, cat: { bebris_2: 1 , } , },
		{ href: 'wSuNvEBsqk0' , title: 'Урок 061' 				, cat: { bebris_2: 1 , } , },
		{ href: 'aerMJJzxWUs' , title: 'Урок 062' 				, cat: { bebris_2: 1 , } , },
		{ href: '-TpkXgLV0Ys' , title: 'Урок 063' 				, cat: { bebris_2: 1 , } , },
		{ href: '1eKG1EyLU0k' , title: 'Урок 064' 				, cat: { bebris_2: 1 , } , },
		{ href: 'n75lEDx87mM' , title: 'Урок 065' 				, cat: { bebris_2: 1 , } , },
		{ href: 'LBnXzY3pz6g' , title: 'Урок 066' 				, cat: { bebris_2: 1 , } , },
		{ href: 'mH6Jca_o268' , title: 'Урок 067' 				, cat: { bebris_2: 1 , } , },
		{ href: 'voKmU5AfbwI' , title: 'Урок 068' 				, cat: { bebris_2: 1 , } , },
		{ href: 'L_tXur1LVG4' , title: 'Урок 069' 				, cat: { bebris_2: 1 , } , },
		{ href: 'rEmN3IMoCYg' , title: 'Урок 070' 				, cat: { bebris_2: 1 , } , },
		{ href: 'SkDiQtjFm00' , title: 'Урок 071' 				, cat: { bebris_2: 1 , } , },
		{ href: 'AqmgQBe741g' , title: 'Урок 072' 				, cat: { bebris_2: 1 , } , },
		{ href: 'BaWEgNWccLM' , title: 'Урок 073' 				, cat: { bebris_2: 1 , } , },
		{ href: 'BGQTAMHPHSk' , title: 'Урок 074' 				, cat: { bebris_2: 1 , } , },
		{ href: 'uccQ6SFpbvs' , title: 'Урок 075' 				, cat: { bebris_2: 1 , } , },
		{ href: 'YyybAN8abio' , title: 'Урок 076' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ylCsklDbyD4' , title: 'Урок 077' 				, cat: { bebris_2: 1 , } , },
		{ href: 'RM0xj_rJuJA' , title: 'Урок 078' 				, cat: { bebris_2: 1 , } , },
		{ href: 'wu5HW88zdBs' , title: 'Урок 079' 				, cat: { bebris_2: 1 , } , },
		{ href: 'njoAWvfJvGw' , title: 'Урок 080' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Edx-q4GSYKw' , title: 'Урок 081' 				, cat: { bebris_2: 1 , } , },
		{ href: 'pNBj4vVBCQE' , title: 'Урок 082' 				, cat: { bebris_2: 1 , } , },
		{ href: 'v09RNPdOFPw' , title: 'Урок 083' 				, cat: { bebris_2: 1 , } , },
		{ href: 'uU8IdfLtAUE' , title: 'Урок 084' 				, cat: { bebris_2: 1 , } , },
		{ href: 'mtZh7u_fWlg' , title: 'Урок 085' 				, cat: { bebris_2: 1 , } , },
		{ href: 'fNZOGDWS1bI' , title: 'Урок 086' 				, cat: { bebris_2: 1 , } , },
		{ href: 'XZaA6YHblsk' , title: 'Урок 087' 				, cat: { bebris_2: 1 , } , },
		{ href: 'LicM_0QgOXc' , title: 'Урок 088' 				, cat: { bebris_2: 1 , } , },
		{ href: 'xlyvXTjujfM' , title: 'Урок 089' 				, cat: { bebris_2: 1 , } , },
		{ href: 'mMBCt0fz4sU' , title: 'Урок 090' 				, cat: { bebris_2: 1 , } , },
		{ href: 'LB-FLaeeVTY' , title: 'Урок 091' 				, cat: { bebris_2: 1 , } , },
		{ href: 'z6KQp0sPPlc' , title: 'Урок 092' 				, cat: { bebris_2: 1 , } , },
		{ href: 'zJswzDK9nmU' , title: 'Урок 093' 				, cat: { bebris_2: 1 , } , },
		{ href: 'x-LHIK_jLbA' , title: 'Урок 094' 				, cat: { bebris_2: 1 , } , },
		{ href: 'W6ej4s1D-uU' , title: 'Урок 095' 				, cat: { bebris_2: 1 , } , },
		{ href: 'UxX1Ca2w7iY' , title: 'Урок 096' 				, cat: { bebris_2: 1 , } , },
		{ href: 'w2Vfv78JRJs' , title: 'Урок 097' 				, cat: { bebris_2: 1 , } , },
		{ href: 'vTwVkeNhL9w' , title: 'Урок 098' 				, cat: { bebris_2: 1 , } , },
		{ href: 'lb7BIFd7hkU' , title: 'Урок 099' 				, cat: { bebris_2: 1 , } , },
		{ href: 'uMnSSiu9x-I' , title: 'Урок 100' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Zkc-HfcTxYg' , title: 'Урок 101' 				, cat: { bebris_2: 1 , } , },
		{ href: 'tKnbjHXOWN8' , title: 'Урок 102' 				, cat: { bebris_2: 1 , } , },
		{ href: 'vZ4DztlPmlE' , title: 'Урок 103' 				, cat: { bebris_2: 1 , } , },
		{ href: '-5vtErTryRg' , title: 'Урок 104' 				, cat: { bebris_2: 1 , } , },
		{ href: '4ILINM-gqJc' , title: 'Урок 105' 				, cat: { bebris_2: 1 , } , },
		{ href: 'gCCiksORLrE' , title: 'Урок 106' 				, cat: { bebris_2: 1 , } , },
		{ href: 'xJB1jAnwZq8' , title: 'Урок 107' 				, cat: { bebris_2: 1 , } , },
		{ href: 'L8dJyY7bwA8' , title: 'Урок 108' 				, cat: { bebris_2: 1 , } , },
		{ href: 'WmLP5zSdXkg' , title: 'Урок 109' 				, cat: { bebris_2: 1 , } , },
		{ href: '_MVbl3J4gLk' , title: 'Урок 110' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Z0U4jE0b5kE' , title: 'Урок 111' 				, cat: { bebris_2: 1 , } , },
		{ href: '4O_tfXXjbPE' , title: 'Урок 112' 				, cat: { bebris_2: 1 , } , },
		{ href: 'OUUofLkQpBg' , title: 'Урок 113' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Ja2f3ArctNU' , title: 'Урок 114' 				, cat: { bebris_2: 1 , } , },
		{ href: 'fyITxgKw6aM' , title: 'Урок 115' 				, cat: { bebris_2: 1 , } , },
		{ href: 'hDo-ksJ1vCA' , title: 'Урок 116' 				, cat: { bebris_2: 1 , } , },
		{ href: '6F9fPzJXT3o' , title: 'Урок 117' 				, cat: { bebris_2: 1 , } , },
		{ href: '6wwJ4xt3Mcc' , title: 'Урок 118' 				, cat: { bebris_2: 1 , } , },
		{ href: 'PudAuKV-JUA' , title: 'Урок 119' 				, cat: { bebris_2: 1 , } , },
		{ href: 'c47tfixwjmg' , title: 'Урок 120' 				, cat: { bebris_2: 1 , } , },
		{ href: 'DQ6i0kfwZsc' , title: 'Урок 121' 				, cat: { bebris_2: 1 , } , },
		{ href: 'CDucvH4DGwk' , title: 'Урок 122' 				, cat: { bebris_2: 1 , } , },
		{ href: '9FL2Fgxlrx4' , title: 'Урок 123' 				, cat: { bebris_2: 1 , } , },
		{ href: 'qSH1nyNiVpk' , title: 'Урок 124' 				, cat: { bebris_2: 1 , } , },
		{ href: '9qfvYw6yliA' , title: 'Урок 125' 				, cat: { bebris_2: 1 , } , },
		{ href: 'nMYs6du8Xq4' , title: 'Урок 126' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Is-CpxGBypU' , title: 'Урок 127' 				, cat: { bebris_2: 1 , } , },
		{ href: 'SuZ1e0DraRM' , title: 'Урок 128' 				, cat: { bebris_2: 1 , } , },
		{ href: 'acPBXU2hhy8' , title: 'Урок 129' 				, cat: { bebris_2: 1 , } , },
		{ href: 'waUoMLhDPNE' , title: 'Урок 130' 				, cat: { bebris_2: 1 , } , },
		{ href: '1aSBuFMUQxg' , title: 'Урок 131' 				, cat: { bebris_2: 1 , } , },
		{ href: 'VIjjiAjH2xs' , title: 'Урок 132' 				, cat: { bebris_2: 1 , } , },
		{ href: '5wQ7WAns-RU' , title: 'Урок 133' 				, cat: { bebris_2: 1 , } , },
		{ href: '57oyWTqbqRg' , title: 'Урок 134' 				, cat: { bebris_2: 1 , } , },
		{ href: 'znF7hxcMMdY' , title: 'Урок 135' 				, cat: { bebris_2: 1 , } , },
		{ href: '971qeC8FV38' , title: 'Урок 136' 				, cat: { bebris_2: 1 , } , },
		{ href: 'vbEQqdym3tY' , title: 'Урок 137' 				, cat: { bebris_2: 1 , } , },
		{ href: 'jI0KsioJ_yc' , title: 'Урок 138' 				, cat: { bebris_2: 1 , } , },
		{ href: '5o2o9yvM3ac' , title: 'Урок 139' 				, cat: { bebris_2: 1 , } , },
		{ href: '2monc4wtm_U' , title: 'Урок 140' 				, cat: { bebris_2: 1 , } , },
		{ href: 'OheAtXhdvck' , title: 'Урок 141' 				, cat: { bebris_2: 1 , } , },
		{ href: 'PLKI9VJa0Q0' , title: 'Урок 142' 				, cat: { bebris_2: 1 , } , },
		{ href: 'aCqxPOa0H-k' , title: 'Урок 143' 				, cat: { bebris_2: 1 , } , },
		{ href: 'O7p9wTcIBvs' , title: 'Урок 144' 				, cat: { bebris_2: 1 , } , },
		{ href: 'EDc9Rzuos_g' , title: 'Урок 145' 				, cat: { bebris_2: 1 , } , },
		{ href: 'AdsiHDc3Gdc' , title: 'Урок 146' 				, cat: { bebris_2: 1 , } , },
		{ href: '0KDNnhQjUVA' , title: 'Урок 147' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ScvhZRM5aQ8' , title: 'Урок 148' 				, cat: { bebris_2: 1 , } , },
		{ href: 'DhPZFqqoGZw' , title: 'Урок 149' 				, cat: { bebris_2: 1 , } , },
		{ href: '5LN3tGLRikU' , title: 'Урок 150' 				, cat: { bebris_2: 1 , } , },
		{ href: 'YaTRJuFGZs0' , title: 'Урок 151' 				, cat: { bebris_2: 1 , } , },
		{ href: '4JJ6ESt3CpM' , title: 'Урок 152' 				, cat: { bebris_2: 1 , } , },
		{ href: '_xuKPBWQ3lE' , title: 'Урок 153' 				, cat: { bebris_2: 1 , } , },
		{ href: 'JZZ3VN3VGOk' , title: 'Урок 154' 				, cat: { bebris_2: 1 , } , },
		{ href: 'zR619xzB4QA' , title: 'Урок 155' 				, cat: { bebris_2: 1 , } , },
		{ href: 't6IQQpOFxEg' , title: 'Урок 156' 				, cat: { bebris_2: 1 , } , },
		{ href: 'QrAebOX9TgY' , title: 'Урок 157' 				, cat: { bebris_2: 1 , } , },
		{ href: 'RxaLX028ugM' , title: 'Урок 158' 				, cat: { bebris_2: 1 , } , },
		{ href: 'GvKF002zk-Y' , title: 'Урок 159' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ilrKB4uOV_E' , title: 'Урок 160' 				, cat: { bebris_2: 1 , } , },
		{ href: 'tP_4PCmJbvs' , title: 'Урок 161' 				, cat: { bebris_2: 1 , } , },
		{ href: '4cKCGqXKMNs' , title: 'Урок 162' 				, cat: { bebris_2: 1 , } , },
		{ href: 'kvOwU-wZo9M' , title: 'Урок 163' 				, cat: { bebris_2: 1 , } , },
		{ href: 'GvrXPorKkmI' , title: 'Урок 164' 				, cat: { bebris_2: 1 , } , },
		{ href: 'R_VKQo13JmA' , title: 'Урок 165' 				, cat: { bebris_2: 1 , } , },
		{ href: 'vGMflOrXBzY' , title: 'Урок 166' 				, cat: { bebris_2: 1 , } , },
		{ href: 'PY_o4_sdnek' , title: 'Урок 167' 				, cat: { bebris_2: 1 , } , },
		{ href: '9nNigIm1Akk' , title: 'Урок 168' 				, cat: { bebris_2: 1 , } , },
		{ href: 'xBpxRapeiuY' , title: 'Урок 169' 				, cat: { bebris_2: 1 , } , },
		{ href: '-QP4MCBOyzs' , title: 'Урок 170' 				, cat: { bebris_2: 1 , } , },
		{ href: 'lKoNDD5IM9s' , title: 'Урок 171' 				, cat: { bebris_2: 1 , } , },
		{ href: '-7gwcEOxAn8' , title: 'Урок 172' 				, cat: { bebris_2: 1 , } , },
		{ href: '3CfNlzHSSlw' , title: 'Урок 173' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ZwdpRugBQGE' , title: 'Урок 174' 				, cat: { bebris_2: 1 , } , },
		{ href: 'blTyEgvZFyQ' , title: 'Урок 175' 				, cat: { bebris_2: 1 , } , },
		{ href: 'QV88kLOVW2c' , title: 'Урок 176' 				, cat: { bebris_2: 1 , } , },
		{ href: 'i2VRZ9uNKmw' , title: 'Урок 177' 				, cat: { bebris_2: 1 , } , },
		{ href: '0BdQ2W554fo' , title: 'Урок 178' 				, cat: { bebris_2: 1 , } , },
		{ href: 'z9jt_3ISJl8' , title: 'Урок 179' 				, cat: { bebris_2: 1 , } , },
		{ href: 'E7Pc3RA_DJc' , title: 'Урок 180' 				, cat: { bebris_2: 1 , } , },
		{ href: '3P53WrN-qHc' , title: 'Урок 181' 				, cat: { bebris_2: 1 , } , },
		{ href: 'USRViY8eeDE' , title: 'Урок 182' 				, cat: { bebris_2: 1 , } , },
		{ href: 'rCFZh2pS7a0' , title: 'Урок 183' 				, cat: { bebris_2: 1 , } , },
		{ href: '8LcIOOH_TLY' , title: 'Урок 184' 				, cat: { bebris_2: 1 , } , },
		{ href: '55RkCI11h04' , title: 'Урок 185' 				, cat: { bebris_2: 1 , } , },
		{ href: 'v4lfH41hB70' , title: 'Урок 186' 				, cat: { bebris_2: 1 , } , },
		{ href: 'r6tzLI6p-Js' , title: 'Урок 187' 				, cat: { bebris_2: 1 , } , },
		{ href: 'bdhUY3hZaO4' , title: 'Урок 188' 				, cat: { bebris_2: 1 , } , },
		{ href: '1RHT-1gXwQI' , title: 'Урок 189' 				, cat: { bebris_2: 1 , } , },
		{ href: 'jA5BACGbzAU' , title: 'Урок 190' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Sjg1M5T4NVg' , title: 'Урок 191' 				, cat: { bebris_2: 1 , } , },
		{ href: 'iuYjBodS53o' , title: 'Урок 192' 				, cat: { bebris_2: 1 , } , },
		{ href: 'fhiXo0tmZTM' , title: 'Урок 193' 				, cat: { bebris_2: 1 , } , },
		{ href: 'hxOvfSGg3b8' , title: 'Урок 194' 				, cat: { bebris_2: 1 , } , },
		{ href: '_znluEngBpw' , title: 'Урок 195' 				, cat: { bebris_2: 1 , } , },
		{ href: '6k6QwYL6NzA' , title: 'Урок 196' 				, cat: { bebris_2: 1 , } , },
		{ href: 'cN7Hhf8QT8k' , title: 'Урок 197' 				, cat: { bebris_2: 1 , } , },
		{ href: '-RQo0r2Ww_4' , title: 'Урок 198' 				, cat: { bebris_2: 1 , } , },
		{ href: '8MpJY6XPViY' , title: 'Урок 199' 				, cat: { bebris_2: 1 , } , },
		{ href: 'wZWknSluMg8' , title: 'Урок 200' 				, cat: { bebris_2: 1 , } , },
		{ href: 'IxjdanDgqWE' , title: 'Урок 201' 				, cat: { bebris_2: 1 , } , },
		{ href: 't2kyC8K1PGM' , title: 'Урок 202' 				, cat: { bebris_2: 1 , } , },
		{ href: 'bJVW8-1MAKQ' , title: 'Урок 203' 				, cat: { bebris_2: 1 , } , },
		{ href: '3DYSYeGHees' , title: 'Урок 204' 				, cat: { bebris_2: 1 , } , },
		{ href: 'tFzvLQ47oFM' , title: 'Урок 205' 				, cat: { bebris_2: 1 , } , },
		{ href: 'F3e4Y2XSlfk' , title: 'Урок 206' 				, cat: { bebris_2: 1 , } , },
		{ href: 'AZ38r8XzrwI' , title: 'Урок 207' 				, cat: { bebris_2: 1 , } , },
		{ href: 'cIdrYY0ZlPE' , title: 'Урок 208' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ccHftNth5O8' , title: 'Урок 209' 				, cat: { bebris_2: 1 , } , },
		{ href: 'YARyesI3lM8' , title: 'Урок 210' 				, cat: { bebris_2: 1 , } , },
		{ href: 'JSHrZuAy9uo' , title: 'Урок 211' 				, cat: { bebris_2: 1 , } , },
		{ href: 'uER2VzYpbK4' , title: 'Урок 212' 				, cat: { bebris_2: 1 , } , },
		{ href: 'typLVnU2noM' , title: 'Урок 213' 				, cat: { bebris_2: 1 , } , },
		{ href: 'l9Z2Fbs_Pio' , title: 'Урок 214' 				, cat: { bebris_2: 1 , } , },
		{ href: 'iLQWtCKU0_U' , title: 'Урок 215' 				, cat: { bebris_2: 1 , } , },
		{ href: 'lx-HhzfqGVM' , title: 'Урок 216' 				, cat: { bebris_2: 1 , } , },
		{ href: 'tobxRohwPjA' , title: 'Урок 217' 				, cat: { bebris_2: 1 , } , },
		{ href: 'pTOI1PtFheQ' , title: 'Урок 218' 				, cat: { bebris_2: 1 , } , },
		{ href: '7u2Zlfpi6Ts' , title: 'Урок 219' 				, cat: { bebris_2: 1 , } , },
		{ href: 'DwGHGjDPw-o' , title: 'Урок 220' 				, cat: { bebris_2: 1 , } , },
		{ href: '_QTpE9YRIog' , title: 'Урок 221' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ks-mhOUQ2aU' , title: 'Урок 222' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Lgw8E7O2I68' , title: 'Урок 223' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Wuzo002R0K4' , title: 'Урок 224' 				, cat: { bebris_2: 1 , } , },
		{ href: 'l3dyI_ckQ30' , title: 'Урок 225' 				, cat: { bebris_2: 1 , } , },
		{ href: 'k30PW6j0i50' , title: 'Урок 226' 				, cat: { bebris_2: 1 , } , },
		{ href: 'yWD0lq0qim4' , title: 'Урок 227' 				, cat: { bebris_2: 1 , } , },
		{ href: 'MFWUxY-z6nE' , title: 'Урок 228' 				, cat: { bebris_2: 1 , } , },
		{ href: 'bwRD9zg5tb4' , title: 'Урок 229' 				, cat: { bebris_2: 1 , } , },
		{ href: '0-tIcRtT1-A' , title: 'Урок 230' 				, cat: { bebris_2: 1 , } , },
		{ href: 'QgvQcvK-lso' , title: 'Урок 231' 				, cat: { bebris_2: 1 , } , },
		{ href: 'nP2DuCcttjk' , title: 'Урок 232' 				, cat: { bebris_2: 1 , } , },
		{ href: 'LvXaf3U0CxA' , title: 'Урок 233' 				, cat: { bebris_2: 1 , } , },
		{ href: '9D6GbkSmLF8' , title: 'Урок 234' 				, cat: { bebris_2: 1 , } , },
		{ href: 'w9CA-qDPGSk' , title: 'Урок 235' 				, cat: { bebris_2: 1 , } , },
		{ href: 'yvdUvIO4Wio' , title: 'Урок 236' 				, cat: { bebris_2: 1 , } , },
		{ href: 'UJfeqgQS9zA' , title: 'Урок 237' 				, cat: { bebris_2: 1 , } , },
		{ href: '2ABpjUEPBiA' , title: 'Урок 238' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Fceo3f1fxXw' , title: 'Урок 239' 				, cat: { bebris_2: 1 , } , },
		{ href: '6SjnW1QF1JQ' , title: 'Урок 240' 				, cat: { bebris_2: 1 , } , },
		{ href: 'lKy85mitOPo' , title: 'Урок 241' 				, cat: { bebris_2: 1 , } , },
		{ href: 'JxOVqSLIlRg' , title: 'Урок 242' 				, cat: { bebris_2: 1 , } , },
		{ href: 't1gEkIssg3M' , title: 'Урок 243' 				, cat: { bebris_2: 1 , } , },
		{ href: 'yOcwLI426I8' , title: 'Урок 244' 				, cat: { bebris_2: 1 , } , },
		{ href: '3N-40Dw9QWk' , title: 'Урок 245' 				, cat: { bebris_2: 1 , } , },
		{ href: '0vQxLfCmYfI' , title: 'Урок 246' 				, cat: { bebris_2: 1 , } , },
		{ href: 'HEVmZKB6uQs' , title: 'Урок 247' 				, cat: { bebris_2: 1 , } , },
		{ href: 'T-emPJCqi20' , title: 'Урок 248' 				, cat: { bebris_2: 1 , } , },
		{ href: 'gzKOAleAJ28' , title: 'Урок 249' 				, cat: { bebris_2: 1 , } , },
		{ href: 'yEi4PESsnD8' , title: 'Урок 250' 				, cat: { bebris_2: 1 , } , },
		{ href: 'cpNfQQm8ppk' , title: 'Урок 251' 				, cat: { bebris_2: 1 , } , },
		{ href: 'cuMVO-E9mDk' , title: 'Урок 252' 				, cat: { bebris_2: 1 , } , },
		{ href: 'RV1fTUlUBxs' , title: 'Урок 253' 				, cat: { bebris_2: 1 , } , },
		{ href: 'xn87N8mbCFI' , title: 'Урок 254' 				, cat: { bebris_2: 1 , } , },
		{ href: '4_eJuqL7KjQ' , title: 'Урок 255' 				, cat: { bebris_2: 1 , } , },
		{ href: '62kfQH0uwIU' , title: 'Урок 256' 				, cat: { bebris_2: 1 , } , },
		{ href: 'x3pFKllH8qQ' , title: 'Урок 257' 				, cat: { bebris_2: 1 , } , },
		{ href: 'r7CD2z0_cCw' , title: 'Урок 258' 				, cat: { bebris_2: 1 , } , },
		{ href: 'cO9m5FhSfeQ' , title: 'Урок 259' 				, cat: { bebris_2: 1 , } , },
		{ href: '0pCDJrj2h9c' , title: 'Урок 260' 				, cat: { bebris_2: 1 , } , },
		{ href: 'GEorr2nlRyw' , title: 'Урок 261' 				, cat: { bebris_2: 1 , } , },
		{ href: 'fqJX2kpgjKI' , title: 'Урок 262' 				, cat: { bebris_2: 1 , } , },
		{ href: 'HLnsxWAdwBM' , title: 'Урок 263' 				, cat: { bebris_2: 1 , } , },
		{ href: 'tGdVrBWCULk' , title: 'Урок 264' 				, cat: { bebris_2: 1 , } , },
		{ href: '7htKKtUUU9Q' , title: 'Урок 265' 				, cat: { bebris_2: 1 , } , },
		{ href: 'HGwwoQB0BIA' , title: 'Урок 266' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Gwzq4L4eH10' , title: 'Урок 267' 				, cat: { bebris_2: 1 , } , },
		{ href: '93ZV3zIV5lE' , title: 'Урок 268' 				, cat: { bebris_2: 1 , } , },
		{ href: 'qjb3rtyG8po' , title: 'Урок 269' 				, cat: { bebris_2: 1 , } , },
		{ href: 'yC_fCbaaP-0' , title: 'Урок 270' 				, cat: { bebris_2: 1 , } , },
		{ href: '7uXgtLHhtd0' , title: 'Урок 271' 				, cat: { bebris_2: 1 , } , },
		{ href: 'zyqB5_bQY_U' , title: 'Урок 272' 				, cat: { bebris_2: 1 , } , },
		{ href: 'zMMSBNL4S4Q' , title: 'Урок 273' 				, cat: { bebris_2: 1 , } , },
		{ href: '32LQLh2Zl4Y' , title: 'Урок 274' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ynJfeW4dY4g' , title: 'Урок 275' 				, cat: { bebris_2: 1 , } , },
		{ href: 'jEQhf2BMDLE' , title: 'Урок 276' 				, cat: { bebris_2: 1 , } , },
		{ href: 'b4axnYorr1o' , title: 'Урок 277' 				, cat: { bebris_2: 1 , } , },
		{ href: 'IgnBYQQH81s' , title: 'Урок 278' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Fd6HIISRxLw' , title: 'Урок 279' 				, cat: { bebris_2: 1 , } , },
		{ href: 'LHaUmWpHynQ' , title: 'Урок 280' 				, cat: { bebris_2: 1 , } , },
		{ href: 'KauDR8zhnUg' , title: 'Урок 281' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ZcLn9XZ9hJ4' , title: 'Урок 282' 				, cat: { bebris_2: 1 , } , },
		{ href: 'PHoQ5C1_s5M' , title: 'Урок 283' 				, cat: { bebris_2: 1 , } , },
		{ href: 'JpZZ8LsbDOM' , title: 'Урок 284' 				, cat: { bebris_2: 1 , } , },
		{ href: 'w1exWPiXJnE' , title: 'Урок 285' 				, cat: { bebris_2: 1 , } , },
		{ href: 'vDfNqN07Nrg' , title: 'Урок 286' 				, cat: { bebris_2: 1 , } , },
		{ href: '7oXKFv4HBvU' , title: 'Урок 287' 				, cat: { bebris_2: 1 , } , },
		{ href: '-SXjBKFc5A8' , title: 'Урок 288' 				, cat: { bebris_2: 1 , } , },
		{ href: '6pY3oKwsuVo' , title: 'Урок 289' 				, cat: { bebris_2: 1 , } , },
		{ href: 't4mUFGMJ200' , title: 'Урок 290' 				, cat: { bebris_2: 1 , } , },
		{ href: 'GaBhdIumMjw' , title: 'Урок 291' 				, cat: { bebris_2: 1 , } , },
		{ href: 'iQ2gs95tS3w' , title: 'Урок 292' 				, cat: { bebris_2: 1 , } , },
		{ href: '5mFaI_cnaB8' , title: 'Урок 293' 				, cat: { bebris_2: 1 , } , },
		{ href: 'y8pcQGaMKI0' , title: 'Урок 294' 				, cat: { bebris_2: 1 , } , },
		{ href: 'aMFoPLFTK10' , title: 'Урок 295' 				, cat: { bebris_2: 1 , } , },
		{ href: 'JUK5V_e7APs' , title: 'Урок 296' 				, cat: { bebris_2: 1 , } , },
		{ href: 'RIPD00DDXEk' , title: 'Урок 297' 				, cat: { bebris_2: 1 , } , },
		{ href: 'QnPG4-AXL1Y' , title: 'Урок 298' 				, cat: { bebris_2: 1 , } , },
		{ href: 'seJGk3K9Hhc' , title: 'Урок 299' 				, cat: { bebris_2: 1 , } , },
		{ href: 'H4-rXitQBN8' , title: 'Урок 300' 				, cat: { bebris_2: 1 , } , },
		{ href: 'pxfF4MkYdPc' , title: 'Урок 301' 				, cat: { bebris_2: 1 , } , },
		{ href: 'IWAGej8reHQ' , title: 'Урок 302' 				, cat: { bebris_2: 1 , } , },
		{ href: 'eE_sqWpL-lo' , title: 'Урок 303' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Cl8fpgT9kpU' , title: 'Урок 304' 				, cat: { bebris_2: 1 , } , },
		{ href: 'tqepHq1HYIU' , title: 'Урок 305' 				, cat: { bebris_2: 1 , } , },
		{ href: 'zCiBUcG3RQc' , title: 'Урок 306' 				, cat: { bebris_2: 1 , } , },
		{ href: 'MC0EPmPnTH8' , title: 'Урок 307' 				, cat: { bebris_2: 1 , } , },
		{ href: '34voAP9kXs8' , title: 'Урок 308' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Bj81J-FkBZw' , title: 'Урок 309' 				, cat: { bebris_2: 1 , } , },
		{ href: 'a2NXNeUKhcU' , title: 'Урок 310' 				, cat: { bebris_2: 1 , } , },
		{ href: 'FCaNCyP2Gig' , title: 'Урок 311' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ULXdcFczelM' , title: 'Урок 312' 				, cat: { bebris_2: 1 , } , },
		{ href: 'tuchsCyihk0' , title: 'Урок 313' 				, cat: { bebris_2: 1 , } , },
		{ href: 'LfE7sTtbAaM' , title: 'Урок 314' 				, cat: { bebris_2: 1 , } , },
		{ href: 'CN2Qyb6cDDQ' , title: 'Урок 315' 				, cat: { bebris_2: 1 , } , },
		{ href: 'V5PCgdjBQf8' , title: 'Урок 316' 				, cat: { bebris_2: 1 , } , },
		{ href: 'rNFbSDcKxFQ' , title: 'Урок 317' 				, cat: { bebris_2: 1 , } , },
		{ href: '3vSqFLZ47cc' , title: 'Урок 318' 				, cat: { bebris_2: 1 , } , },
		{ href: 'EEMmcyY2nvc' , title: 'Урок 319' 				, cat: { bebris_2: 1 , } , },
		{ href: 'NHpmiyw-03A' , title: 'Урок 320' 				, cat: { bebris_2: 1 , } , },
		{ href: '3au2M8X2GDg' , title: 'Урок 321' 				, cat: { bebris_2: 1 , } , },
		{ href: 'cTtcmycgs9o' , title: 'Урок 322' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Y3De1dEjMpI' , title: 'Урок 323' 				, cat: { bebris_2: 1 , } , },
		{ href: '89Mf5EveRw4' , title: 'Урок 324' 				, cat: { bebris_2: 1 , } , },
		{ href: 'M_yHSraY7do' , title: 'Урок 325' 				, cat: { bebris_2: 1 , } , },
		{ href: 'JdBOtCUWatQ' , title: 'Урок 326' 				, cat: { bebris_2: 1 , } , },
		{ href: 'LHYEp_lcNL0' , title: 'Урок 327' 				, cat: { bebris_2: 1 , } , },
		{ href: 'dmbTKXB2SNY' , title: 'Урок 328' 				, cat: { bebris_2: 1 , } , },
		{ href: 'JogvXBORbjA' , title: 'Урок 329' 				, cat: { bebris_2: 1 , } , },
		{ href: 'X9V_1oESx88' , title: 'Урок 330' 				, cat: { bebris_2: 1 , } , },
		{ href: 'i2cHBmDAuHk' , title: 'Урок 331' 				, cat: { bebris_2: 1 , } , },
		{ href: 'QThDpJOHdyc' , title: 'Урок 332' 				, cat: { bebris_2: 1 , } , },
		{ href: 'eHnidhHkJ38' , title: 'Урок 333' 				, cat: { bebris_2: 1 , } , },
		{ href: 'NzG1Hio8rO0' , title: 'Урок 334' 				, cat: { bebris_2: 1 , } , },
		{ href: '1hU5sys68ko' , title: 'Урок 335' 				, cat: { bebris_2: 1 , } , },
		{ href: 'fGxRBo8Prko' , title: 'Урок 336' 				, cat: { bebris_2: 1 , } , },
		{ href: 'nGnDta7MpTw' , title: 'Урок 337' 				, cat: { bebris_2: 1 , } , },
		{ href: '6Bt5ADjFeds' , title: 'Урок 338' 				, cat: { bebris_2: 1 , } , },
		{ href: 'dJFqUIPiv8g' , title: 'Урок 339' 				, cat: { bebris_2: 1 , } , },
		{ href: 'znGWaujz4dY' , title: 'Урок 340' 				, cat: { bebris_2: 1 , } , },
		{ href: 'A3ooQxRR9Ro' , title: 'Урок 341' 				, cat: { bebris_2: 1 , } , },
		{ href: 'u1F2FeOQhWU' , title: 'Урок 342' 				, cat: { bebris_2: 1 , } , },
		{ href: 'qUzK1fl16LU' , title: 'Урок 343' 				, cat: { bebris_2: 1 , } , },
		{ href: 'HkFu9dLvRfQ' , title: 'Урок 344' 				, cat: { bebris_2: 1 , } , },
		{ href: '7YLcqzSlRDI' , title: 'Урок 345' 				, cat: { bebris_2: 1 , } , },
		{ href: 'RzI876ZqBes' , title: 'Урок 346' 				, cat: { bebris_2: 1 , } , },
		{ href: '51tkabW1aBg' , title: 'Урок 347' 				, cat: { bebris_2: 1 , } , },
		{ href: 'HaZq2d-aeLQ' , title: 'Урок 348' 				, cat: { bebris_2: 1 , } , },
		{ href: 'LpT_JOOORv0' , title: 'Урок 349' 				, cat: { bebris_2: 1 , } , },
		{ href: 'm8d-2vUTABA' , title: 'Урок 350' 				, cat: { bebris_2: 1 , } , },
		{ href: '187MuBk2syY' , title: 'Урок 351' 				, cat: { bebris_2: 1 , } , },
		{ href: '5g6hKBtcWjU' , title: 'Урок 352' 				, cat: { bebris_2: 1 , } , },
		{ href: 'zTtL9HF0Bso' , title: 'Урок 353' 				, cat: { bebris_2: 1 , } , },
		{ href: '6rFJkFq5f0s' , title: 'Урок 354' 				, cat: { bebris_2: 1 , } , },
		{ href: 'tMUvi-TiN9Y' , title: 'Урок 355' 				, cat: { bebris_2: 1 , } , },
		{ href: 'JQakF36fdwc' , title: 'Урок 356' 				, cat: { bebris_2: 1 , } , },
		{ href: 'twxjcoiGSYI' , title: 'Урок 357' 				, cat: { bebris_2: 1 , } , },
		{ href: 'LfB9hgzxu2M' , title: 'Урок 358' 				, cat: { bebris_2: 1 , } , },
		{ href: 'CoBA-riyrH8' , title: 'Урок 359' 				, cat: { bebris_2: 1 , } , },
		{ href: 'kLXfzU6AEsg' , title: 'Урок 360' 				, cat: { bebris_2: 1 , } , },
		{ href: 'm4GfvtDlJzU' , title: 'Урок 361' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ccEH93IAjzU' , title: 'Урок 362' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Vb_qQIGrsC4' , title: 'Урок 363' 				, cat: { bebris_2: 1 , } , },
		{ href: '_8uTU-rGo3s' , title: 'Урок 364' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Ytc7X2E1OJE' , title: 'Урок 365' 				, cat: { bebris_2: 1 , } , },
		{ href: 'xw6BVpuZ3Xg' , title: 'Урок 366' 				, cat: { bebris_2: 1 , } , },
		{ href: '7mtDOgXlR44' , title: 'Урок 367' 				, cat: { bebris_2: 1 , } , },
		{ href: 'jHefHakYP-Y' , title: 'Урок 368' 				, cat: { bebris_2: 1 , } , },
		{ href: 'iL5pqF2fb5E' , title: 'Урок 369' 				, cat: { bebris_2: 1 , } , },
		{ href: 'GGewEZk_-YY' , title: 'Урок 370' 				, cat: { bebris_2: 1 , } , },
		{ href: 'PzhOMbNnGEk' , title: 'Урок 371' 				, cat: { bebris_2: 1 , } , },
		{ href: '22E641d--ZY' , title: 'Урок 372' 				, cat: { bebris_2: 1 , } , },
		{ href: '8z2Vf3MvNZg' , title: 'Урок 373' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Zu6y9vy68rc' , title: 'Урок 374' 				, cat: { bebris_2: 1 , } , },
		{ href: 'SxRqzZSfIWA' , title: 'Урок 375' 				, cat: { bebris_2: 1 , } , },
		{ href: 'bautx0H74O8' , title: 'Урок 376' 				, cat: { bebris_2: 1 , } , },
		{ href: '8ErrpA15xr4' , title: 'Урок 377' 				, cat: { bebris_2: 1 , } , },
		{ href: 'B7L8Qp60WQ8' , title: 'Урок 378' 				, cat: { bebris_2: 1 , } , },
		{ href: 'dkBIfciHgew' , title: 'Урок 379' 				, cat: { bebris_2: 1 , } , },
		{ href: 'anzAcaI6Jwg' , title: 'Урок 380' 				, cat: { bebris_2: 1 , } , },
		{ href: '6O5TZvoiiKE' , title: 'Урок 381' 				, cat: { bebris_2: 1 , } , },
		{ href: 'uy1wHQ622gY' , title: 'Урок 382' 				, cat: { bebris_2: 1 , } , },
		{ href: 'gQRKzYFATVk' , title: 'Урок 383' 				, cat: { bebris_2: 1 , } , },
		{ href: 'SH_zHCpHsDw' , title: 'Урок 384' 				, cat: { bebris_2: 1 , } , },
		{ href: 'DcrhX1aKM5I' , title: 'Урок 385' 				, cat: { bebris_2: 1 , } , },
		{ href: '3zJzXGdOE2I' , title: 'Урок 386' 				, cat: { bebris_2: 1 , } , },
		{ href: '1bzkfOQmSg8' , title: 'Урок 387' 				, cat: { bebris_2: 1 , } , },
		{ href: 'fGORovrvsCI' , title: 'Урок 388' 				, cat: { bebris_2: 1 , } , },
		{ href: 'qSN1dvKOpXQ' , title: 'Урок 389' 				, cat: { bebris_2: 1 , } , },
		{ href: '6CARMEA6fsk' , title: 'Урок 390' 				, cat: { bebris_2: 1 , } , },
		{ href: '_xx5zV_IXbs' , title: 'Урок 391' 				, cat: { bebris_2: 1 , } , },
		{ href: 'HOSri9CY6Ys' , title: 'Урок 392' 				, cat: { bebris_2: 1 , } , },
		{ href: '48pBCJU3V84' , title: 'Урок 393' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ynmDfdQn0Fc' , title: 'Урок 394' 				, cat: { bebris_2: 1 , } , },
		{ href: 'vJq2km5EBso' , title: 'Урок 395' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ztpH0Logihg' , title: 'Урок 396' 				, cat: { bebris_2: 1 , } , },
		{ href: 'KmEE5i4OFjI' , title: 'Урок 397' 				, cat: { bebris_2: 1 , } , },
		{ href: '4SRBCZQmM6o' , title: 'Урок 398' 				, cat: { bebris_2: 1 , } , },
		{ href: 'LJP3bk9xDFY' , title: 'Урок 399' 				, cat: { bebris_2: 1 , } , },
		{ href: 'FJ65SemRRrc' , title: 'Урок 400' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Lc0tLH9ZBPE' , title: 'Урок 401' 				, cat: { bebris_2: 1 , } , },
		{ href: 'f5JFIChEaH4' , title: 'Урок 402' 				, cat: { bebris_2: 1 , } , },
		{ href: 'HX_wvEAuZHE' , title: 'Урок 403' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Z0bmkNxxpDY' , title: 'Урок 404' 				, cat: { bebris_2: 1 , } , },
		{ href: 'hUsrtQn6RRU' , title: 'Урок 405' 				, cat: { bebris_2: 1 , } , },
		{ href: 'KLYlFAGjCHY' , title: 'Урок 406' 				, cat: { bebris_2: 1 , } , },
		{ href: '-0MD7pqU5Ew' , title: 'Урок 407' 				, cat: { bebris_2: 1 , } , },
		{ href: 'TptP-hqwuGY' , title: 'Урок 408' 				, cat: { bebris_2: 1 , } , },
		{ href: 'RUOA1dO9iiw' , title: 'Урок 409' 				, cat: { bebris_2: 1 , } , },
		{ href: 'GgIDvcQQgq0' , title: 'Урок 410' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ZsutifmL32k' , title: 'Урок 411' 				, cat: { bebris_2: 1 , } , },
		{ href: 'siKj3zND3mQ' , title: 'Урок 412' 				, cat: { bebris_2: 1 , } , },
		{ href: 'twOr7oqoJdI' , title: 'Урок 413' 				, cat: { bebris_2: 1 , } , },
		{ href: 'QIu-mvOEwTQ' , title: 'Урок 414' 				, cat: { bebris_2: 1 , } , },
		{ href: 'vinzJJZzzNA' , title: 'Урок 415' 				, cat: { bebris_2: 1 , } , },
		{ href: 'kM09ncKEvHo' , title: 'Урок 416' 				, cat: { bebris_2: 1 , } , },
		{ href: '2IKlGOk4ZnM' , title: 'Урок 417' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Xid2RdySr5o' , title: 'Урок 418' 				, cat: { bebris_2: 1 , } , },
		{ href: '5oZhkFdl5g4' , title: 'Урок 419' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Z_1vYa6kf8Q' , title: 'Урок 420' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Xs2rTSJT6NE' , title: 'Урок 421' 				, cat: { bebris_2: 1 , } , },
		{ href: 'as42O7HqnPA' , title: 'Урок 422' 				, cat: { bebris_2: 1 , } , },
		{ href: 'zijCu60S4QM' , title: 'Урок 423' 				, cat: { bebris_2: 1 , } , },
		{ href: 'eWs32sfc3jU' , title: 'Урок 424' 				, cat: { bebris_2: 1 , } , },
		{ href: 'vlU52s7dAPA' , title: 'Урок 425' 				, cat: { bebris_2: 1 , } , },
		{ href: 'o1R0o6ABfus' , title: 'Урок 426' 				, cat: { bebris_2: 1 , } , },
		{ href: 'P0nhXZoWJOI' , title: 'Урок 427' 				, cat: { bebris_2: 1 , } , },
		{ href: '0j7-Cbi0d54' , title: 'Урок 428' 				, cat: { bebris_2: 1 , } , },
		{ href: 'zt8QkOAvJq4' , title: 'Урок 429' 				, cat: { bebris_2: 1 , } , },
		{ href: 'mHwX4dPIsqo' , title: 'Урок 430' 				, cat: { bebris_2: 1 , } , },
		{ href: 'h4pg4O-Zhqw' , title: 'Урок 431' 				, cat: { bebris_2: 1 , } , },
		{ href: 'S-CuTiOKQmU' , title: 'Урок 432' 				, cat: { bebris_2: 1 , } , },
		{ href: 'aIVCK9pj_Ek' , title: 'Урок 433' 				, cat: { bebris_2: 1 , } , },
		{ href: '5QENCrtGZz8' , title: 'Урок 434' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Ll4TZDpy2yI' , title: 'Урок 435' 				, cat: { bebris_2: 1 , } , },
		{ href: 'YzlZl19n7gg' , title: 'Урок 436' 				, cat: { bebris_2: 1 , } , },
		{ href: '22zj4KtfvpM' , title: 'Урок 437' 				, cat: { bebris_2: 1 , } , },
		{ href: 'NYzxEc6gKgo' , title: 'Урок 438' 				, cat: { bebris_2: 1 , } , },
		{ href: 'uPa4RrF6KRo' , title: 'Урок 439' 				, cat: { bebris_2: 1 , } , },
		{ href: 'gXtZUKkcQgA' , title: 'Урок 440' 				, cat: { bebris_2: 1 , } , },
		{ href: 'a8i0pZjdaTI' , title: 'Урок 441' 				, cat: { bebris_2: 1 , } , },
		{ href: 'PbZibC1SVwM' , title: 'Урок 442' 				, cat: { bebris_2: 1 , } , },
		{ href: 'uDaP0QubPU0' , title: 'Урок 443' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ijKvwt0ASpw' , title: 'Урок 444' 				, cat: { bebris_2: 1 , } , },
		{ href: 'd9TgqP0myr0' , title: 'Урок 445' 				, cat: { bebris_2: 1 , } , },
		{ href: 'v1MZ3R7sHkM' , title: 'Урок 446' 				, cat: { bebris_2: 1 , } , },
		{ href: 'dOrfNVFMwc8' , title: 'Урок 447' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Z-4NF0Zr7dM' , title: 'Урок 448' 				, cat: { bebris_2: 1 , } , },
		{ href: '-o3rfZP-cII' , title: 'Урок 449' 				, cat: { bebris_2: 1 , } , },
		{ href: 'FjD1b1-3A2Y' , title: 'Урок 450' 				, cat: { bebris_2: 1 , } , },
		{ href: 'uSaWsCA3P5E' , title: 'Урок 451' 				, cat: { bebris_2: 1 , } , },
		{ href: '9hj56ggGhlE' , title: 'Урок 452' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ZHypE6IGTAw' , title: 'Урок 453' 				, cat: { bebris_2: 1 , } , },
		{ href: 'YcnoCyxIPbs' , title: 'Урок 454' 				, cat: { bebris_2: 1 , } , },
		{ href: 'I0GA-7DqBSc' , title: 'Урок 455' 				, cat: { bebris_2: 1 , } , },
		{ href: 'oDQpEFhHU8o' , title: 'Урок 456' 				, cat: { bebris_2: 1 , } , },
		{ href: 'iPYmPzC1jos' , title: 'Урок 457' 				, cat: { bebris_2: 1 , } , },
		{ href: 'SoEuhBCGAm0' , title: 'Урок 458' 				, cat: { bebris_2: 1 , } , },
		{ href: 'qTKKaE7-8A4' , title: 'Урок 459' 				, cat: { bebris_2: 1 , } , },
		{ href: 'jaqNfqC8sPM' , title: 'Урок 460' 				, cat: { bebris_2: 1 , } , },
		{ href: 'EWQq_jwQjP4' , title: 'Урок 461' 				, cat: { bebris_2: 1 , } , },
		{ href: 'HzjJhBePx0E' , title: 'Урок 462' 				, cat: { bebris_2: 1 , } , },
		{ href: '0eDwh7Fwpe8' , title: 'Урок 463' 				, cat: { bebris_2: 1 , } , },
		{ href: 'nO80dad93KE' , title: 'Урок 464' 				, cat: { bebris_2: 1 , } , },
		{ href: 'H9CRg1ysT7w' , title: 'Урок 465' 				, cat: { bebris_2: 1 , } , },
		{ href: 'V4Bu8OPuiSQ' , title: 'Урок 466' 				, cat: { bebris_2: 1 , } , },
		{ href: 'zjvg7GBj-zw' , title: 'Урок 467' 				, cat: { bebris_2: 1 , } , },
		{ href: 'hHQIbIBypXM' , title: 'Урок 468' 				, cat: { bebris_2: 1 , } , },
		{ href: 'MtBIaWM3_Lo' , title: 'Урок 469' 				, cat: { bebris_2: 1 , } , },
		{ href: 'hPjFN1WogLk' , title: 'Урок 470' 				, cat: { bebris_2: 1 , } , },
		{ href: 'mbOh1KZXEP0' , title: 'Урок 471' 				, cat: { bebris_2: 1 , } , },
		{ href: 'DiERIwfGNUs' , title: 'Урок 472' 				, cat: { bebris_2: 1 , } , },
		{ href: 'ZgSrIH1xTiw' , title: 'Урок 473' 				, cat: { bebris_2: 1 , } , },
		{ href: 'sRV37NcgSCM' , title: 'Урок 474' 				, cat: { bebris_2: 1 , } , },
		{ href: '8GK7NUZGPlc' , title: 'Урок 475' 				, cat: { bebris_2: 1 , } , },
		{ href: 'elzZj39MbU4' , title: 'Урок 476' 				, cat: { bebris_2: 1 , } , },
		{ href: 'nvkXk82AqAg' , title: 'Урок 477' 				, cat: { bebris_2: 1 , } , },
		{ href: '3xmOjbDJZgY' , title: 'Урок 478' 				, cat: { bebris_2: 1 , } , },
		{ href: '2A0E_4Lka7A' , title: 'Урок 479' 				, cat: { bebris_2: 1 , } , },
		{ href: 'kDWJJskXtbQ' , title: 'Урок 480' 				, cat: { bebris_2: 1 , } , },
		{ href: 'Vn0w_PdX5Ss' , title: 'Урок 481' 				, cat: { bebris_2: 1 , } , },

		{ href: 'kGBtJu4zKBU' , title: 'Полиглот - Урок 1' 		, cat: { polyglot: 1 , }, },
		{ href: '-JW2kYd7vYw' , title: 'Полиглот - Урок 2' 		, cat: { polyglot: 1 , }, },
		{ href: 'IIcPA2cJ3Ek' , title: 'Полиглот - Урок 3' 		, cat: { polyglot: 1 , }, },
		{ href: 'NBXlgPgRgGk' , title: 'Полиглот - Урок 4' 		, cat: { polyglot: 1 , }, },
		{ href: 'ETPrgmTBP9M' , title: 'Полиглот - Урок 5' 		, cat: { polyglot: 1 , }, },
		{ href: 'rHVyOOJ3tS0' , title: 'Полиглот - Урок 6' 		, cat: { polyglot: 1 , }, },
		{ href: 'W5p2YHTdUnQ' , title: 'Полиглот - Урок 7' 		, cat: { polyglot: 1 , }, },
		{ href: 'F2-hM97uZK4' , title: 'Полиглот - Урок 8' 		, cat: { polyglot: 1 , }, },
		{ href: '0R_V2rn0TGk' , title: 'Полиглот - Урок 9' 		, cat: { polyglot: 1 , }, },
		{ href: 'O4JfIRRfZNA' , title: 'Полиглот - Урок 10' 	, cat: { polyglot: 1 , }, },
		{ href: 'YrWEP5sZsaQ' , title: 'Полиглот - Урок 11' 	, cat: { polyglot: 1 , }, },
		{ href: 'EiPXalvH4m8' , title: 'Полиглот - Урок 12' 	, cat: { polyglot: 1 , }, },
		{ href: 'cqlJM4pap3M' , title: 'Полиглот - Урок 13' 	, cat: { polyglot: 1 , }, },
		{ href: 'uThXvqXLr_4' , title: 'Полиглот - Урок 14' 	, cat: { polyglot: 1 , }, },
		{ href: 'sZAy566Hvyw' , title: 'Полиглот - Урок 15' 	, cat: { polyglot: 1 , }, },
		{ href: 'ghNEMWmpsNw' , title: 'Полиглот - Урок 16' 	, cat: { polyglot: 1 , }, },

	],
 },
{ 	
	id: 'kvn', title: 'КВН', 
	nav: [ 
		{ id: 'all' 			, title: 'Все' 			, },
	],
	arr: [
		{ href: 'THhb8t6ZJt0', title: 'Агутин и Варум (М.Галустян, И.Буяновский)' 						, },
		{ href: 'cMq_HGycfKY', title: 'Анна Семенович - Тотальный диктант (Уральские Пельмени)' 		, },
		{ href: 'OGT19htl5vs', title: 'Анфиса Чехова ушла от мужа' 										, },
		{ href: 'eIg2zHtAuDY', title: 'Байки про жюри (М.Галустян)' 									, },
		{ href: 'uBYzeEX5qyc', title: 'Балет ГИБДД (М.Галустян, И.Буяновский)' 							, },
		{ href: 'zsNy_Prv4M0', title: 'Белокурая Жози (Сибирские сибиряки)' 							, },
		{ href: '9cZ8C-6WSAI', title: 'Будущие космонавты в поезде (И.Ласточкин, В.Борисов, Ю.Ткач)' 	, },
		{ href: 'bk3weYlGZZI', title: 'Встреча одноклассников (Уральские Пельмени)' 					, },
		{ href: 'HcqTQU256jM', title: 'Выставка собак (БГУ)'  											, },
		{ href: 'OuJrxaMxnNA', title: 'Вышибала в библиотеке (М.Галустян)' 								, },
		{ href: 'XMWiN1mnw7c', title: 'Гадя Петрович (М.Галустян, А.Ревва)' 							, },
		{ href: 'glTt1pSsE_E', title: 'Михаил Брюк (Уральские Пельмени)' 								, },
		{ href: '_I7I2DdRv54', title: 'Новогоднее обращение (Транзит)'  								, },
		{ href: 'GSsNFJDXjlw', title: 'Похмелье после НГ (БГУ)'  										, },
		{ href: 'wVEww05OMGg', title: 'Рэп президента'  												, },
		{ href: '0zg2ek5lw1I', title: 'Училка на уроке (Дежа Вю)'  										, },








	], 
},
{ 	
	id: 'clips', title: 'Клипы', 
	nav: [ 
		{ id: 'all' 	, title: 'Все' 			, },
		{ id: 'en' 		, title: 'Зарубежные' 	, },
		{ id: 'ru' 		, title: 'Наши' 		, },
	],
	arr: [
		{ href: 'YytZ5h9nOOo' , title: 'Alice Deejay - The lonely one' 					, cat: { en: 1, } , },
		{ href: 'zfXBNQMj2SE' , title: 'Alizee - Moi Lolita' 							, cat: { en: 1, } , },
		{ href: 'zEf423kYfqk' , title: 'Becky G & Natti Natasha - Sin pijama' 			, cat: { en: 1, } , },
		{ href: 'C-u5WLJ9Yk4' , title: 'Britney Spears - Baby one More Time' 			, cat: { en: 1, } , },
		{ href: 'Yy5cKX4jBkQ' , title: 'Britney Spears - Born to make you happy' 		, cat: { en: 1, } , },
		{ href: 'Q4VK9_CfOLQ' , title: 'Britney Spears - Crazy' 						, cat: { en: 1, } , },
		{ href: 'IlV7RhT6zHs' , title: 'Britney Spears - I\'m not a girl' 				, cat: { en: 1, } , },
		{ href: '4vvBAONkYwI' , title: 'Britney Spears - Lucky' 						, cat: { en: 1, } , },
		{ href: 'CduA0TULnow' , title: 'Britney Spears - Oops!...I did it again' 		, cat: { en: 1, } , },
		{ href: 'PZYSiWHW8V0' , title: 'Britney Spears - Overprotected' 				, cat: { en: 1, } , },
		{ href: 't0bPrt69rag' , title: 'Britney Spears - Sometimes' 					, cat: { en: 1, } , },
		{ href: 'AJWtLf4-WWs' , title: 'Britney Spears - Stronger' 						, cat: { en: 1, } , },
		{ href: '5RQxHyCTi18' , title: 'Captain Jack - Drill Instructor' 				, cat: { en: 1, } , },
		{ href: '4zHm_6AQ7CY' , title: 'Dr.Alban - It\'s my life' 						, cat: { en: 1, } , },
		{ href: '3GA3yFM22ao' , title: 'E-Type - Africa' 								, cat: { en: 1, } , },
		{ href: 'svnE-eQVtPM' , title: 'E-Type - Angels Crying' 						, cat: { en: 1, } , },
		{ href: 'HoT1GFrMods' , title: 'E-Type - Here I go again' 						, cat: { en: 1, } , },
		{ href: 'pbWLvwE8zfw' , title: 'E-Type - I just wanna be with you' 				, cat: { en: 1, } , },
		{ href: 'tp-iwlt75to' , title: 'E-Type - Russian lullaby' 						, cat: { en: 1, } , },
		{ href: '7w1HeDqYCU4' , title: 'E-Type - This is the way' 						, cat: { en: 1, } , },
		{ href: 'QNJL6nfu__Q' , title: 'Michael Jackson - They don\'t care about us' 	, cat: { en: 1, } , },
		{ href: 'CQAT5qdG8tI' , title: 'Queen - The show must go on' 					, cat: { en: 1, } , },
		{ href: 'dZDj2CnG5dE' , title: 'Ricky Martin - The cup of life' 				, cat: { en: 1, } , },
		{ href: 'kc7X3q27b34' , title: 'Robert Miles - Children' 						, cat: { en: 1, } , },
		{ href: '1M6q3PRxI3Q' , title: 'Sash & Dr.Alban - Colour the World' 			, cat: { en: 1, } , },
		{ href: 'e-xkH8BWMXk' , title: 'Агата Кристи - Моряк' 							, cat: { ru: 1, } , },
		{ href: 'JNxCwfnr-8w' , title: 'АлисА - Трасса Е-95' 							, cat: { ru: 1, } , },
		{ href: 'soyckS4wgFM' , title: 'Бутырка - Кольщик' 								, cat: { ru: 1, } , },
		{ href: 'MUxlAV_47q0' , title: 'Валерий Меладзе - Белые птицы' 					, cat: { ru: 1, } , },
		{ href: 'LLCU65HYFkU' , title: 'Василий Лавров - Колотушка' 					, cat: { ru: 1, } , },
		{ href: '3rfuOcn-wRM' , title: 'Виктор Зинчук - Каприс №24. Паганини' 			, cat: { ru: 1, } , },
		{ href: '90ArrDU0p0M' , title: 'Восток - Танец жёлтых листьев' 					, cat: { ru: 1, } , },
		{ href: 'hHcvEIFBJEs' , title: 'Евгений Кемеровский - Ностальгия' 				, cat: { ru: 1, } , },
		{ href: 'DF6W1XD25Dc' , title: 'Звери - До скорой встречи' 						, cat: { ru: 1, } , },
		{ href: 'qf0ibAffJWA' , title: 'И.Салтыкова - Бай-бай' 							, cat: { ru: 1, } , },
		{ href: '-p6vBTg-wXA' , title: 'И.Салтыкова - Солнечный друг' 					, cat: { ru: 1, } , },
		{ href: 'YjHtjSd7i6E' , title: 'Катя Лель - Долетай' 							, cat: { ru: 1, } , },
		{ href: 'DZFwi8Tm7dE' , title: 'Л.Черникова - Влюблённый самолёт' 				, cat: { ru: 1, } , },
		{ href: 'cGgbQFOK_L4' , title: 'Лицей - Осень' 									, cat: { ru: 1, } , },
		{ href: 'ngsWYx0XN2I' , title: 'Натали - Ветер с моря дул' 						, cat: { ru: 1, } , },
		{ href: '6J5kwV_gpeA' , title: 'Нэнси - Дым сигарет с ментолом' 				, cat: { ru: 1, } , },
		{ href: 'tO91c8vbT7A' , title: 'Руки Вверх - Крошка моя' 						, cat: { ru: 1, } , },
		{ href: 'cKyUHTF4vRc' , title: 'С.Жуков & Боня и Кузьмич - Королева красоты' 	, cat: { ru: 1, } , },
		{ href: 'DLHlBWXtTjQ' , title: 'С.Рерих - Ладошки' 								, cat: { ru: 1, } , },
		{ href: 'ttWZ-Fa1PBE' , title: 'Севара - Там нет меня' 							, cat: { ru: 1, } , },
		{ href: 'fp0uP2FwgYE' , title: 'Стас Костюшкин - Опа Анапа' 					, cat: { ru: 1, } , },
		{ href: 'T6kVFmf0soY' , title: 'Юлия Савичева - Сердцебиение' 					, cat: { ru: 1, } , },

/*
		{ href: '' , title: '' 					, cat: { : 1, } , },
		{ href: '' , title: '' 					, cat: { : 1, } , },
		{ href: '' , title: '' 					, cat: { : 1, } , },
		{ href: '' , title: '' 					, cat: { : 1, } , },
		{ href: '' , title: '' 					, cat: { : 1, } , },
*/







	], 
},

{ 	
	id: 'sport', title: 'Спорт', 
	nav: [ 
		{ id: 'all' 		, title: 'Все' 			, },
	],
	arr: [

		{ href: 'mbeub_iDA0s' , title: 'Moby - Bring Sally up (timer)' 											, cat: { sport: 1 		, } , },


	], 
},
{ 	
	id: 'focus', title: 'Фокусы', 
	nav: [ 
		{ id: 'all' 		, title: 'Все' 			, },
	],
	arr: [
		{ href: 'cGyocPsApHk', title: 'Sacred Riana' 						, },

	], 
},







];













